### ISSUE TITLE
Checkbox for "Add Scroll To Top button" seems amiss

### ISSUE THREAD

**Issue by IzzySoft** [soscripted/sox#366] opened 2018-09-28 21:42 UTC
### Installed Version:
2.3.8 DEV  Environment: undefined

### Current Behaviour
Looks line the check box for "Add Scroll To Top button" has disappeared:

> [![screenshot][1]][1]

That makes it impossible to switch this feature off. Not that I want to, but others might :wink:

  [1]: https://i.stack.imgur.com/18DGe.png

---

### SOX Errors logged to the browser console -- F12 (if available)
unlikely to be relevant, the only line I found:

    SOX:  inlineEditorEverywhere error: sox.Stack.using not found

---

### Steps to reproduce
Just click the icon in the MetaCollider™ to open SOX settings.

---

### Features Enabled
Again subject to change, just started going through the settings one by one:

    ["Appearance-alignBadgesByClass","Appearance-colorAnswerer","Appearance-displayName","Appearance-dragBounty","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Appearance-showTagWikiLinkOnTagPopup","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-hiddenCommentsIndicator","Comments-onlyShowCommentActionsOnHover","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-pasteImagesDirectly","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideJustHotMetaPosts","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-shareLinksPrivacy","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-hideCertainQuestions","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-openLinksInNewTab"]

**Comment by shu8** [comment] 2018-09-29 10:31
Thanks for the bug report, I'll try looking into it soon!

The console error you got seems like another separate bug but I will look
into that too!

**Comment by shu8** [comment] 2018-10-06 13:55
@IzzySoft Please could you right click on the `add scroll to top button` and click 'inspect element' and screenshot what comes up? I can't reproduce it :/

**Comment by IzzySoft** [comment] 2018-10-06 14:53
Yes, I can:

![HTML](https://i.imgur.com/nkimKtZ.png)

Looks like the checkbox is hidden. So, one more screenshot:

![HTML with CSS](https://i.imgur.com/QimlCDZ.png)

See: `display: none !important`. If that wasn't you, it must collide with some other UserScript or UserStyle. Though the name of the rule looks weird. Clicking on the rule points to "inline stylesheet", with a bunch of rules from SOUP again – but I couldn't find that rule there. Couldn't even make it show by overriding CSS on the element itself (display:block visibility:visible, both with !important) – which seems very strange. Disabled SOUP and reloaded – no change. Disabled all other UserScripts – nada. Disabled all UserStyles – niente. Out of ideas what I could try from my end now.

**Comment by shu8** [comment] 2018-10-06 19:46
@IzzySoft Thanks for the thorough debugging! I can't understand what's happening here 😆 Does this happen on a specific site, or is the checkbox hidden in all of them?

Please could you paste the entire block of styles that clicking the weird rule takes you to? I could try seeing if there's any SOX rule within there!

**Comment by shu8** [comment] 2018-10-06 19:56
@IzzySoft Also, for the other error you got, just underneath it there should be a `inlineEditorEverywhere: Stack object:` followed by another line of the object -- could you paste that here too please? :)

**Comment by IzzySoft** [comment] 2018-10-06 22:03
> Does this happen on a specific site, or is the checkbox hidden in all of them?

All I've checked. Need to check at work on Monday if the issue is present there as well; I vaguely remember it is not, and the difference would be the token being present there.

> Please could you paste the entire block of styles that clicking the weird rule takes you to?

Sure: https://pastebin.com/i1Eht1Mv (was too fooking long; what the heck is that long list of URLs there?)

> just underneath it there should be a `inlineEditorEverywhere: Stack object:` …

Afraid not:

    SOX:  inlineEditorEverywhere error: sox.Stack.using not found    sox.common.js:32:13
    soup JS fixes applied

No more SOX after that. Just a new one before that:

    SOX:  There was an error loading the feature "Appearance-colorAnswerer". Please raise an issue on GitHub, and copy the following error log:
    TypeError: this.querySelector(...) is null   sox.common.js:38:13


Ugh. Another issue to open?

PS: Why are the buttons "Close and comment" and "Comment" just inverted compared to GitLab? Guess that's why you see close/reopen so often within a single minute … Almost happened to me now :rofl:

**Comment by shu8** [comment] 2018-10-06 22:12
@IzzySoft Thanks! Those CSS rules really are weird! :/ It seems like it's hiding all social links and buttons and buttons like 'back to top', 'scroll to top' along with it. Do you have any extensions other than uBlock origin installed that hide 'social' buttons?

---

I think the 2nd debug line only comes if debugging is enabled -- could you check it is still enabled please?

---

Don't worry about opening another issue, I'll make sure I look into that too! Which page were you on when it happened?

---

I've never used gitlab so I didn't know that! Although, I don't remember seeing many close/reopens myself!

**Comment by IzzySoft** [comment] 2018-10-06 23:06
> Do you have any extensions other than uBlock origin installed that hide 'social' buttons?

None that I'm aware of (just went through the list again). Only one CSS, but that's not active on SE sites (deactivated it nevertheless, no effect). But even if, I find it very strange that I can't even override that on the object itself (`style="display:block …"`). But true enough: as soon as I change the ID, the check box shows up. Sufficient to just add a letter to the end, like "ScrollToTopp".

> I think the 2nd debug line only comes if debugging is enabled -- could you check it is still enabled please?

As the link at the end of settings say "Enable Debugging", I'd say it's not active. Wait: on that page the error is not present in console. I only seem to have that on Android.SE (link says the same there). Just verified here: https://android.stackexchange.com/q/29447/16575

Not from SOX, but I love this kind of lines:

    Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.

**Comment by IzzySoft** [comment] 2018-10-06 23:10
PS: Just disabled the mega-block in "inspect element". A few seconds later the check box showed up. So at least it's clear now which rule is responsible. Remains the question who establishes it.

**Comment by shu8** [comment] 2018-10-07 12:18
@IzzySoft Nice! it's an interesting way it uses to hide it! Glad it's sorted though :)

---

Just to clarify -- is it the `inlineEditorEverywhere` error only happens on Android? If so, could you check SR too, as it may be to do with you being a mod there?

**Comment by IzzySoft** [comment] 2018-10-07 12:45
Got that `inlineEditorEverywhere` error also on SR, e.g. here: https://softwarerecs.stackexchange.com/q/52574/185

As for that check-box: If I need it I now know how to get to it. Still arguing with myself whether to disable that Fanboy list or not: this might be the first culprit I encountered, who knows if there are more. It's a bit crazy to block a simple ID like this without leaving a chance to counter that (I tried and failed). Checking what that list holds feels like 50:50 (half of it is useful, the other half crazy). Guess I kick it altogether.

**Comment by shu8** [comment] 2018-11-04 20:28
@IzzySoft the inline editor everywhere issue should be fixed in [the latest dev version](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

That check box thing is pretty annoying! If you could just edit the list and remove the go to top selector that would be the best because it's a pretty common button that can be useful sometimes!

**Closed by shu8** 2018-11-04 20:28 UTC
Labels: bug

**Comment by IzzySoft** [comment] 2018-11-05 14:42
Thanks! That error was replaced now by

    There was an error loading the feature "Editing-inlineEditorEverywhere". Please raise an issue on GitHub, and copy the following error log:
TypeError: sox.Stack.using is not a function

:scream:

And why the heck does the preview suddenly not work here at Github? Strange …

Editing that list won't do any good, as the rule would be back at the next update. A "counter rule" should work, or removing that list. Not urgent for me, though, so don't invest too much time in it :wink:

**Comment by shu8** [comment] 2018-11-05 18:04
Great 😂 I'll try getting it fixed this weekend!

I think the preview was working for me yesterday! Must just be a temporary
bug!

**Comment by IzzySoft** [comment] 2018-11-05 19:40
Take your time – I just found this checking the console, so it doesn't seem really urgent :wink:

As for the preview: it's broken for me on my second machine as well. If it's currently broken for you, too, I'll just wait and see tomorrow. A quick search didn't show anything, Github status says "all green".

**Comment by shu8** [comment] 2018-11-09 22:08
@IzzySoft I can't reproduce it :/ Which browser are you on again? (sorry, I keep forgetting!) 

The preview was working for me! Is it working now?
