### ISSUE TITLE
Score of other answers not showing

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#375] opened 2019-01-06 07:20 UTC
### Installed Version: 2.3.21DEV  Environment: Tampermonkey

![image](https://user-images.githubusercontent.com/7231077/50733301-2ccc9780-11b1-11e9-87d8-b10f2667f300.png)

### Current Behaviour
Score of other answers not showing
---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-displayName","Appearance-dragBounty","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideJustHotMetaPosts","Sidebar-hideHireMe","Sidebar-hideChatSidebar","Sidebar-hideLoveThisSite","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksPrivacy","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-hideCertainQuestions","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-openLinksInNewTab","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by shu8** [comment] 2019-01-08 18:40
Thanks for the bug report! I've reproduced it and will work on a fix ASAP!

**Comment by shu8** [comment] 2019-01-08 20:39
Fixed in [dev 2.3.23](https://github.com/soscripted/sox/raw/dev/sox.user.js) @SmartManoj :)

**Closed by shu8** 2019-01-08 20:39 UTC
Labels: bug, confirmed

**Comment by SmartManoj** [comment] 2019-11-09 22:28
Feature missing ?

**Comment by shu8** [comment] 2019-11-12 09:52
@SmartManoj please can you make another issue for this. It makes it easier to track and for me to manage.

I also can't reproduce this immediately so could you provide more details in the new issue?
