### ISSUE TITLE
Tabular suggester stats are out of whack on tag wiki suggestions

### ISSUE THREAD

**Issue by TuggyNE** [soscripted/sox#154] opened 2016-12-05 23:21 UTC
### Installed Version: 2.0.1l  Environment: Pale Moon 26.5.0 x64 Win 10

---
###  Expected Behavior
Table on http://stackoverflow.com/review/suggested-edits/14505413 should show 517 | 34 | N/A.

---
### Actual Behavior
Table on http://stackoverflow.com/review/suggested-edits/14505413 shows 5/1.

---
### SOX Errors logged to the browser console (if available)

---
### Steps to reproduce
Go to a tag wiki/excerpt suggestion and click (more). Disable the script and repeat. Compare the statistics given.

**Comment by shu8** [comment] 2016-12-07 08:02
Thanks for the bug report. 

I've reproduced it and I'll try getting it fixed over the weekend :)

**Comment by shu8** [comment] 2016-12-10 17:43
@TuggyNE fixed in [dev ad](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

It turns out it was actually broken on *all* edits -- the regex for the bottom part only took into account single digit numbers, so it basically only worked on numbers less than 10! :/

Thanks for reporting it, and please could you check whether it is actually fixed for you? :)

**Closed by shu8** 2016-12-10 17:43 UTC
Labels: bug, confirmed, in progress, ready
