### ISSUE TITLE
Closure blocks overlap with post title or are misaligned

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#181] opened 2016-12-23 05:19 UTC
### Current Behaviour

Reasons for closure is posted as part of a search: red = Closed; orange = Duplicate; blue = Migrated

The closed box overlaps with the question title in some instances on [TeX - LaTeX](http://tex.stackexchange.com):

![image](https://cloud.githubusercontent.com/assets/1776164/21447599/d85d985e-c88b-11e6-8bae-e3fe8e701816.png)

They are not aligned in the same way on [Meta.SE](http://meta.stackexchange.com) (perhaps related):

![image](https://cloud.githubusercontent.com/assets/1776164/21447618/2c22ddfa-c88c-11e6-94a1-933238bc17db.png)

---

### SOX Errors logged to the browser console -- F12 (if available)

---

### Steps to reproduce

On TeX.SE: http://tex.stackexchange.com/search?tab=votes&q=closed%3a1
On Meta.SE: http://meta.stackexchange.com/search?q=closed%3A1

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-bulletReplace","Appearance-colorAnswerer","Appearance-fixedTopbar","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Unsorted-alwaysShowImageUploadLinkBox","Unsorted-parseCrossSiteLinks","Unsorted-quickAuthorInfo","Unsorted-shareLinksMarkdown","Unsorted-warnNotLoggedIn"]

**Comment by shu8** [comment] 2016-12-23 13:52
@wgrundlingh Do you happen to have SOUP installed? I can reproduce this when I enable SOUP, so I'll see if I can come up with a fix :)

**Comment by wgrundlingh** [comment] 2016-12-23 16:16
@shu8 I do have SOUP installed, yes.

**Comment by shu8** [comment] 2016-12-23 16:43
@wgrundlingh @wgrundlingh fixed in [dev f](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

thanks for the bug report! :) We've had a few conflicts with SOUP, and I'm really keen on keeping the 2 scripts compatible with each other, because they complement each other so well, so please do tell me if you see anything similar! :)

**Closed by shu8** 2016-12-23 16:43 UTC
Labels: bug, compatibility, confirmed, in progress, ready

**Comment by IStoleThePies** [comment] 2016-12-30 01:59
@shu8 Just a suggestion, but perhaps you should change `$('.question-summary .answer-hyperlink, .question-summary .question-hyperlink, .question-summary .result-link a').css('display', 'inline-block');` to `$('.question-summary .answer-hyperlink, .question-summary .question-hyperlink, .question-summary .result-link a').css('display', 'inline');`, since inline-block causes the text to shift for bounties like [these](https://astronomy.stackexchange.com/?tab=featured).

**Comment by shu8** [comment] 2016-12-30 13:16
@IStoleThePies sure, it'll be done in dev x
