### ISSUE TITLE
Fix topbar position

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#96] opened 2016-08-13 21:11 UTC
**Installed Version: 1.X.X  |  Environment: Chrome/Tampermonkey**
Note: Firefox not Chrome

**Expected Behavior**
>How do you expect the feature to work?
Click a comment in the user profile to open it in context.  The comment should be readable, entirely below the topbar.

**Actual Behavior**
>How is the feature currently behaving?
The top several lines of the comment are hidden behind the topbar.  The topbar doesn't "reserve the space", so writing other content to the screen isn't aware that the topbar space is already in use.
Issue reported with previous version, slated for fixing in this version.  

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

**Steps to reproduce**
>What steps did you take to reproduce the issue?

![capture](https://cloud.githubusercontent.com/assets/10065766/17645621/03996644-6179-11e6-9530-4a377e0facbe.PNG)

**Comment by shu8** [comment] 2016-08-13 21:21
Duplicate of #74

**Closed by shu8** 2016-08-13 21:21 UTC
