### ISSUE TITLE
"Show when the post's author was last seen and whether they are registered"not working

### ISSUE THREAD

**Issue by AmperAndSand** [soscripted/sox#438] opened 2019-09-05 12:30 UTC
**Describe the bug**
The feature, "Show when the post's author was last seen and whether they are registered" doesn't seem to be working. I've only noticed this today despite it working fine yesterday.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable above mentioned feature and then go to a post such as https://gaming.stackexchange.com/questions/87258/whats-the-best-strategy-to-keep-the-chaos-low/90107 or https://superuser.com/questions/694349/how-do-i-repair-the-corrupted-files-found-by-sfc-scannow-windows-resource-pro
2. Notice that info on when the post's author was last seen and whether they are registered are not shown.

**SOX errors logged in console**
https://paste.ubuntu.com/p/S7QvpDKW7Z/

**Environment**
SOX version: 2.5.39DEV
Platform: Tampermonkey

Chrome 75.0.3770.142 (Official Build) (64-bit)
---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-scrollToTop","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-copyCommentsLink","Comments-showCommentScores","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-kbdAndBullets","Editing-titleEditDiff","Flags-flagOutcomeTime","Flags-flagPercentages","Sidebar-linkedToFrom","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-warnNotLoggedIn","Extras-dailyReviewBar"]

**Comment by shu8** [comment] 2019-09-05 12:42
Thanks for the bug report. I can't reproduce this unfortunately, but the log output you've added is helpful because it's showing SOX can't find the user links for some reason.

Have you installed any other extensions or userscripts recently that might be messing with the HTML/order of elements in the page?

Could you also try run ```$('.question, .answer, .reviewable-post').find('.post-signature:last-child .user-details a[href^="/users"]')``` in the browser console and paste/screenshot the output on any question the feature isn't working for you? That's the selector that the feature is using, which should give the post-signature elements on the page hopefully

**Comment by AmperAndSand** [comment] 2019-09-05 16:54
I don't recall installing new user scripts or extensions since the last time it worked, but some of my extensions might have updated. Here's a screenshot of the browser console after running the above command:

![sox_screenshot_browser_console](https://user-images.githubusercontent.com/1404745/64361709-addd7680-d03f-11e9-9f13-3b1608a7d3fb.png)

**Comment by shu8** [comment] 2019-09-05 17:11
Hmm that's quite weird :/ The only thing I can notice that's different in the two screenshots is that in the working one, SOUP JS fixes seem to be applied _after_ the SOX feature has run but in the broken one, it's before.

Is it always working now, or is it on-and-off? If so, could you temporarily disable SOUP to see if that fixes it? If it does happen to be that, I'll try looking into if there's a SOUP fix that might be conflicting with this feature. (Although, I have SOUP installed and still can't manage to reproduce :/ it might be a weird timing thing between the 2 scripts!)

**Comment by AmperAndSand** [comment] 2019-09-06 12:50
It's always working now. I can't reproduce the issue again after it worked the last time. I'll let you know if I encounter the issue again.

**Comment by shu8** [comment] 2019-09-13 10:50
I'm going to close this issue for now. Please re-open it and comment here if this happens again! :)

**Closed by shu8** 2019-09-13 10:50 UTC
Labels: bug
