### ISSUE TITLE
SOX has now completely stopped working

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#23] opened 2016-03-07 23:26 UTC
SOX has now stopped working completely. I don't know whether it's because the changes you made to make it compatible with SOUP. 

Clues:

1. Any changes made in the SOX config dialog do not stick.

2. If I reload the browser page I see a brief flash of a blue diamond in the top bar, which is then covered by the SOX cogwheels.

3. Yesterday, SOX was working. The blue diamond was then to the right of the cogwheeels. Later it moved to the left. Now it seems to be underneath.

I've tried all 3 versions of SOX.

Browser Firefox latest on Windows.

SOUP 1.54.4

Browser has been restarted.

**Comment by enki-code** [comment] 2016-03-08 01:36
@DavidPostill  Is it one specific function that isn't working correctly? Are you getting anything in the console?   We made some changes to the meta question alert function, it no longer displays the diamond on meta sites.

**Comment by shu8** [comment] 2016-03-08 07:19
@DavidPostill You need to click `reset` and choose your options again, I made changes to the way the settings were stored and run, and forgot to add a check for the old version :/

**Comment by DavidPostill** [comment] 2016-03-08 10:10
@enki-code It looks like almost every function is not working. 

Console:

`soup injecting fixes
SOUP.user.js (line 1921)
soup init complete
337631 (line 30)
SOX error: There was an error loading the feature "Appearance-fixedTopbar". Please raise an issue on GitHub, and copy the following error log.
sox.user.js (line 194)
Error details:
sox.user.js (line 195)
ReferenceError: StackExchange is not defined
	

sox.user.js (line 196)
SOX error: There was an error loading the feature "Appearance-metaNewQuestionAlert". Please raise an issue on GitHub, and copy the following error log.
sox.user.js (line 194)
Error details:
sox.user.js (line 195)
ReferenceError: StackExchange is not defined
	

sox.user.js (line 196)
SOX error: There was an error loading the feature "Appearance-hideSearchBar". Please raise an issue on GitHub, and copy the following error log.
sox.user.js (line 194)
Error details:
sox.user.js (line 195)
ReferenceError: StackExchange is not defined
	

sox.user.js (line 196)
SOX error: There was an error loading the feature "Comments-quickCommentShortcutsMain". Please raise an issue on GitHub, and copy the following error log.
sox.user.js (line 194)
Error details:
sox.user.js (line 195)
ReferenceError: StackExchange is not defined
	

sox.user.js (line 196)
soup setup complete
337631 (line 30)
soup JS fixes applied
337631 (line 30)`

@shu8 Reset has already been tried. I reset, made a couple of changes and saved.

When I open settings again random setting are unticked (the flags options are one such example).

I also get top bar corruption after roughly every second page reload.

![screenshot - 08_03_2016 10_08_23](https://cloud.githubusercontent.com/assets/7079224/13598502/0046165c-e516-11e5-99da-6fe00457477f.png)

**Comment by shu8** [comment] 2016-03-08 17:25
Which version is this? Can you make sure its the `master` version, and that it is version `1.0.2`?

If it is 1.0.2, it seems the helper functions are not working correctly, but that was (at least I thought it had been) fixed. So could you just replace line 21:

    // @require      https://rawgit.com/soscripted/sox/master/sox.helpers.js?v=1.0.2a`

to 

    // @require      https://rawgit.com/soscripted/sox/master/sox.helpers.js?v=1.0.2b`

(change the final `a` to `b`) to make sure the latest version of the helper functions are being fetched.

**Comment by DavidPostill** [comment] 2016-03-08 18:02
Changed line 21 as requested. Get the following error:

![screenshot - 08_03_2016 18_01_14](https://cloud.githubusercontent.com/assets/7079224/13610923/e556ff36-e557-11e5-891e-c965b4a09a29.png)

**Comment by shu8** [comment] 2016-03-08 19:04
ok @DavidPostill weird... 

Can you try installing this version: https://gist.github.com/shu8/0a275e3e1f1aa8717b24/raw/8a6b54b97e530081f017e6f0a554c2c2ce4ca285/davidpostillDebugging.user.js which I just added a few more console logs to and linked to a different helper function file.

Make sure no other version of SOX is running, and it is only this new version.

Can you paste the console's log after running that version.

thanks for bearing with me! This is pretty weird :/

**Comment by enki-code** [comment] 2016-03-08 19:04
@shu8 I can confirm this.  Fresh install on Chrome/Tampermonkey works just fine and a fresh install on Firefox/Greasemonkey fails.  All the errors in the console say StackExchange not defined, yet, I can access it via the console just fine. 

I suspect this may be a timing issue.

**Comment by shu8** [comment] 2016-03-08 19:28
@enki-code ok, it's probably because Greasemonkey/FF blocks access to objects defined by the webpage...

**Comment by shu8** [comment] 2016-03-08 19:30
@enki-code are you free for chat right now? I have around half an hour

**Comment by enki-code** [comment] 2016-03-08 19:32
@shu8  Yes.

**Comment by shu8** [comment] 2016-03-08 20:04
@DavidPostill To update you...

- we've both reproduced this on FF
- it's because FF doesn't let us access window objects
- we kind of know a fix(es)
- but we need to do other things as well for it to actually work

so, it might not be till tomorrow or even the day after till we can push a fix! :/ 

Sorry! We need to add 'Test on FF' to our non-existent todo list before pushing to master from now on :P 

and thanks for reporting the issue and hanging with us! :)

**Comment by shu8** [comment] 2016-03-09 19:24
@DavidPostill and @enki-code I think I've fixed it. Please could you install this debugging version: https://gist.github.com/shu8/0a275e3e1f1aa8717b24/raw/9526b89f00d22b9023ca60dc9f76976352e5fd64/davidpostillDebugging.user.js and confirm whether it is working for you now?

**Comment by shu8** [comment] 2016-03-09 19:28
And you might be glad to know I've created a checklist issue for the future @DavidPostill: https://github.com/soscripted/sox/issues/24 ;)

**Comment by enki-code** [comment] 2016-03-09 19:48
@shu8 Confirmed working.

**Comment by enki-code** [comment] 2016-03-09 19:56
@DavidPostill The latest fix has been pushed to master, would you mind installing and confirming that this is working for you as well?  Thanks.

**Comment by DavidPostill** [comment] 2016-03-09 21:11
@shu8 @enki-code Confirmed as fixed. Thanks guys ;)

**Comment by shu8** [comment] 2016-03-09 21:20
@DavidPostill You're welcome! :) Thanks for putting up with us and reporting this issue in the first place! :P

**Closed by shu8** 2016-03-09 21:20 UTC
Labels: bug

**Comment by enki-code** [comment] 2016-03-09 21:36
@DavidPostill Feel free to join us in the [chat room](https://chat.stackexchange.com/rooms/35418/sox-originally-soof) anytime.
