### ISSUE TITLE
"Show when post's author last seen"  not working

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#90] opened 2016-08-13 19:41 UTC
**Installed Version: 1.X.X  |  Environment: Chrome/Tampermonkey**

**Expected Behavior**
>How do you expect the feature to work?
The cited information appearing somewhere.

**Actual Behavior**
>How is the feature currently behaving?
No relevant information about authors of either questions or answers appears on the post.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

**Steps to reproduce**
>What steps did you take to reproduce the issue?

**Comment by shu8** [comment] 2016-08-13 21:19
Again, please could you just update #73 and close this.

**Comment by shu8** [comment] 2016-08-13 21:21
Duplicate of #73

**Closed by shu8** 2016-08-13 21:21 UTC
