### ISSUE TITLE
Some broken features

### ISSUE THREAD

**Issue by ooker777** [soscripted/sox#489] opened 2021-08-21 09:20 UTC
It doesn't automatically: 

- convert share link to markdown format, 
- show the last active time below the user profile picture,
- replace the on-topic link with the help link

I use Firefox 89.0.1 (64-bit), SOX 2.7.8DEV

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-highlightQuestions","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Appearance-showTagWikiLinkOnTagPopup","Appearance-hideWelcomeBackMessage","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-kbdAndBullets","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-linkedToFrom","Sidebar-hotNetworkQuestionsFiltering","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-sortByBountyAmount","Extras-copyCode","Extras-openLinksInNewTab","Extras-addOnTopicLinkToSiteSwitcher","Extras-customMagicLinks"]

**Comment by shu8** [comment] 2021-08-30 18:05
Thanks for the bug report. I'll get these fixed ASAP!

**Comment by shu8** [comment] 2021-09-13 15:40
@ooker777 I've finally had time to look at this but can't reproduce the first two bugs in your list on FF or Chrome. Please could you install the latest dev version from this URL: 
https://github.com/soscripted/sox/raw/dev/sox.user.js (v2.7.9 dev) and see if it still happens for you?

The on-topic bug should be fixed now!

**Comment by shu8** [comment] 2021-09-14 11:59
I tried installing the extension but still can't reproduce. Are there any specific steps you take that cause the issue to happen?

**Comment by shu8** [comment] 2021-11-20 12:07
Do you still experience these bugs?

**Closed** 2022-05-17 01:34 UTC
Labels: bug
