### ISSUE TITLE
Corrupted top bar on French Language Beta

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#142] opened 2016-11-07 17:28 UTC
SOX 2.0.2 DEV  Greasemonkey
Windows 7 Home Premium 64 bit, Firefox 49.0.2

Social media icons appearing on top of SOX config icon on https://french.stackexchange.com/

![screenshot - 07_11_2016 17_25_17](https://cloud.githubusercontent.com/assets/7079224/20068031/30aef408-a50f-11e6-84e5-93e97b964295.png)

Note:

- I've not seen this on any other SE site (and due to flagging spam with MetaSmoke and FDSC I have accounts on **lots** of sites.

**Comment by shu8** [comment] 2016-11-07 18:02
@DavidPostill hmm I can't reproduce that. Looks like the CSS hasn't fully loaded...?

Could you try hard-refreshing/trying in a new profile and see if that fixes it please? :)

**Comment by DavidPostill** [comment] 2016-11-07 18:09
Hmm. It goes away if I disable SOUP 1.44.4

**Comment by shu8** [comment] 2016-11-07 19:14
hmm, there must be a SOUP patch for French/a specific of the site that
French has.

I'll look into it, but it's going to have to be the weekend now :( I'm busy
all week! Sorry!

**Comment by DavidPostill** [comment] 2016-11-07 20:23
No problem. It's only cosmetic ;)

-- 
David Postill

**Comment by shu8** [comment] 2016-11-13 14:39
@DavidPostill weird... I can't reproduce this with SOUP enabled either :/

Does it still happen? If it does, please can you right click on the cogs, click 'inspect element' and screenshot and upload whatever pops up?

**Comment by shu8** [comment] 2016-11-13 18:15
@DavidPostill fixed in latest [dev version q](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

**Closed by shu8** 2016-11-13 18:15 UTC
Labels: bug, confirmed, in progress, ready

**Comment by DavidPostill** [comment] 2016-11-13 20:31
Thanks. Confirmed as fixed :)
