### ISSUE TITLE
Fixed topbar prevents user from closing code snippet

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#103] opened 2016-08-28 19:30 UTC
### Installed Version: 1.X.X  Environment: Chrome/Tampermonkey 
2.0.1G
...

###  Expected Behavior
I would be able to close a code snippet when viewing the full page
...

### Actual Behavior
The topbar covers the close button
...

### SOX Errors logged to the browser console (if available)

...

### Steps to reproduce
1. Go to any post with a code snippet (i.e. http://codegolf.stackexchange.com/a/91199)
2. Click "Run code snippet"
3. Click on the "Full page" text that appears to the right of "Hide results"
4. If the topbar is fixed, you won't be able to click "close" (which is at the top right of the page)

(I would recommend having the topbar disappear while you view the full page)

**Comment by shu8** [comment] 2016-08-28 19:50
Thanks for posting this bug! I have reproduced this and am looking into a fix. Hopefully, this will be fixed in the next DEV version. I'll keep you posted on the progress :)

**Comment by fixer1234** [comment] 2016-08-28 20:35
Another manifestation of #74?

**Comment by shu8** [comment] 2016-08-28 20:36
@fixer1234 no, seems different, but still to do with the fixed topbar

**Comment by fixer1234** [comment] 2016-09-09 17:45
Possibly another manifestation, which, hopefully, will be fixed by what's in progress.  In a review queue (Close and LQP), there is a pop-up window for specifying the close reason.  The top of that window has a similar Close "X", which gets tucked under the top bar and not accessible if you want to cancel action on the close vote.

**Comment by shu8** [comment] 2016-10-01 18:32
@fixer1234 fixed in [v2.0.1n](https://github.com/soscripted/sox/raw/fix/sox.user.js). 

About the review queue: does it not work if you scroll up so the top of the dialog is not hidden?

**Closed by shu8** 2016-10-01 18:32 UTC
Labels: bug, confirmed, ready

**Comment by IStoleThePies** [comment] 2016-10-01 18:43
@shu8 I'm sorry, what do you mean?

**Comment by shu8** [comment] 2016-10-01 18:45
@IStoleThePies I was talking about [fixer1234's comment](https://github.com/soscripted/sox/issues/103#issuecomment-245986850) where he said that the top of the review queue dialog was also hidden, but I *think* it should be able to be closed if you scroll to the top of the page...

**Comment by fixer1234** [comment] 2016-10-01 21:06
@shu8 looks like you got a break from school and had a sudden surge of energy.  :-)  Do I understand correctly that the v2.0.1 (merge?) link is the official current release, replacing v2.0.1n?  This should keep me busy for awhile.  Thanks!

**Comment by shu8** [comment] 2016-10-01 21:08
@fixer1234 yeah, my first free weekend! :D 

Yes, the v2.0.1 merge is the most latest official release; you can install it at https://github.com/soscripted/sox/blob/master/sox.user.js.
