### ISSUE TITLE
Suggested difference highlights title difference by line not by word

### ISSUE THREAD

**Issue by SmartManoj** [soscripted/sox#413] opened 2019-07-04 10:03 UTC
https://meta.stackoverflow.com/questions/386853/suggested-difference-highlights-title-difference-by-line-not-by-word

**Comment by double-beep** [comment] 2019-07-04 10:31
Options you are using? Cannot reproduce:

![image](https://user-images.githubusercontent.com/38133098/60660222-f5892b80-9e5f-11e9-9227-ea3031f65435.png)

Any other userscripts you are using?

**Comment by SmartManoj** [comment] 2019-07-04 12:52
Disabled all other userscripts and userstyles.

**Comment by shu8** [comment] 2019-07-04 16:52
From your screenshot in the Meta.SO post:

![](https://i.stack.imgur.com/RvmKf.png)

If you look closely at the left of the title, there is a black toggle icon which would toggle it. Unfortunately your dark theme makes this difficult to see.

Feel free to disable the feature if this isn't something you want. The feature is:

>Make title edits show separately rather than merged in edit suggestions

Under the 'Editing' section in the settings dialog.

Closing this as it isn't a bug, but it is related to #406. I'd welcome any pull requests for helping support the dark theme, but unfortunately this won't be very high priority for me.

**Closed by shu8** 2019-07-04 16:52 UTC
Labels: feature request

**Comment by SmartManoj** [comment] 2019-07-04 17:47
> Options you are using? Cannot reproduce:
> 
> ![image](https://user-images.githubusercontent.com/38133098/60660222-f5892b80-9e5f-11e9-9227-ea3031f65435.png)
> 
> Any other userscripts you are using?

![image](https://user-images.githubusercontent.com/7231077/60682678-cdc2b380-9eb1-11e9-943d-dc1fa8a8b629.png)
@shu8 
Both are different

**Comment by shu8** [comment] 2019-07-04 17:51
Yes, the toggle button toggles which view you see:

![diff](https://user-images.githubusercontent.com/8850830/60682809-a6a5bb00-9e8c-11e9-958b-2f80aa70827f.gif)

**Comment by SmartManoj** [comment] 2019-07-04 17:52
> Options you are using? Cannot reproduce:
> 
> ![image](https://user-images.githubusercontent.com/38133098/60660222-f5892b80-9e5f-11e9-9227-ea3031f65435.png)
> 
> Any other userscripts you are using?

The strikes

**Comment by shu8** [comment] 2019-07-04 17:59
Could you elaborate? I'm not sure what you mean.

**Comment by SmartManoj** [comment] 2019-07-04 18:01
> Yes, the toggle button toggles which view you see:
> 
> ![diff](https://user-images.githubusercontent.com/8850830/60682809-a6a5bb00-9e8c-11e9-958b-2f80aa70827f.gif)

Only insert should be highlighted when toggle is on

**Comment by shu8** [comment] 2019-07-05 20:00
Sorry, still not sure what you mean!

The point of the feature is to just show a before and after view, just like in the [feature request here](https://meta.stackoverflow.com/a/323196), and has [always worked like this](https://meta.stackexchange.com/a/256122)

**Comment by SmartManoj** [comment] 2019-07-06 02:36
> > Options you are using? Cannot reproduce:
> > ![image](https://user-images.githubusercontent.com/38133098/60660222-f5892b80-9e5f-11e9-9227-ea3031f65435.png)
> > Any other userscripts you are using?
> 
> ![image](https://user-images.githubusercontent.com/7231077/60682678-cdc2b380-9eb1-11e9-943d-dc1fa8a8b629.png)
> @shu8
> Both are different

first one is more readable and easy to identify only the difference

**Comment by SmartManoj** [comment] 2019-07-06 02:37
> Options you are using? Cannot reproduce:
> 
> ![image](https://user-images.githubusercontent.com/38133098/60660222-f5892b80-9e5f-11e9-9227-ea3031f65435.png)
> 
> Any other userscripts you are using?

@double-beep How you get this?
