### ISSUE TITLE
Wiki link does not work on /tags page

### ISSUE THREAD

**Issue by IzzySoft** [soscripted/sox#368] opened 2018-10-02 16:43 UTC
### Current Behaviour
When I'm inspecting a question and hover over the tag, the wiki link is shown as expected. If I try the same on the `/tags` page, there is no wiki link.

---

### SOX Errors logged to the browser console -- F12 (if available)
Let me put it the other way around: What is missing in the browser console? The following line:

    SOX:  running showTagWikiLinkOnTagPopup

So it seems that function doesn't run there at all.

---

### Steps to reproduce
* open the `tags/` page on any SE site, e.g. [Android.SE](https://android.stackexchange.com/tags)
* hover the mouse over any tag

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Appearance-showTagWikiLinkOnTagPopup","Comments-commentReplies","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Comments-onlyShowCommentActionsOnHover","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-pasteImagesDirectly","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideJustHotMetaPosts","Sidebar-hideHireMe","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by shu8** [comment] 2018-10-03 20:08
Thanks, I'll get this fixed ASAP!

On Tue, 2 Oct 2018 at 17:43, Izzy <notifications@github.com<mailto:notifications@github.com>> wrote:
Installed Version: 2.3.8 DEV Environment: undefined
Current Behaviour

When I'm inspecting a question and hover over the tag, the wiki link is shown as expected. If I try the same on the /tags page, there is no wiki link.

________________________________
SOX Errors logged to the browser console -- F12 (if available)

Let me put it the other way around: What is missing in the browser console? The following line:

SOX:  running showTagWikiLinkOnTagPopup


So it seems that function doesn't run there at all.

________________________________
Steps to reproduce

  *   open the tags/ page on any SE site, e.g. Android.SE<https://android.stackexchange.com/tags>
  *   hover the mouse over any tag

________________________________
Features Enabled

["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-highlightQuestions","Appearance-isQuestionHot","Appearance-localTimestamps","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Appearance-addTimelineAndRevisionLinks","Appearance-showTagWikiLinkOnTagPopup","Comments-commentReplies","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Comments-onlyShowCommentActionsOnHover","Editing-editComment","Editing-editReasonTooltip","Editing-findAndReplace","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-pasteImagesDirectly","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideCommunityBulletin","Sidebar-hideJustHotMetaPosts","Sidebar-hideHireMe","Sidebar-hideLoveThisSite","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-stickyVoteButtons","Voting-disableVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-sortByBountyAmount","Extras-warnNotLoggedIn","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar","Extras-showQuestionStateInSuggestedEditReviewQueue"]

**Comment by shu8** [comment] 2018-10-06 13:58
@IzzySoft Fixed in [dev 2.3.9](https://github.com/soscripted/sox/raw/dev/sox.user.js)! :)

I just overlooked the tags page so I've enabled it there now!

**Closed by shu8** 2018-10-06 13:58 UTC
Labels: bug, confirmed, in progress, ready

**Comment by IzzySoft** [comment] 2018-10-06 14:58
That's what I thought indeed. Thanks – and confirmed working!
