### ISSUE TITLE
Authors name is added twice to comment in inbox with SOUP enabled

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#7] opened 2016-02-19 20:37 UTC
![screenshot - 19_02_2016 20_35_58](https://cloud.githubusercontent.com/assets/7079224/13188295/843f2100-d748-11e5-9c5b-81f9eb4f3671.png)

**Comment by cullub** [comment] 2016-02-19 21:23
Can't reproduce on FF 44.0.2 Mac.

What browser are you on?

**Comment by DavidPostill** [comment] 2016-02-19 21:35
WIndows 7 64 bit, Firefox 44.0.2 64 bit

**Comment by cullub** [comment] 2016-02-19 22:32
Hmm.  Evidently a windows thing - do you have Chrome? (to test) And could you test in IE?

**Comment by DavidPostill** [comment] 2016-02-19 22:58
Hmm Chrome 48 on Windows "Add the author's name to notifications in the inbox" doesn't work at all. How do I install greasemonkey or test on IE?

**Comment by DavidPostill** [comment] 2016-02-19 23:01
Weird. Now it's not working at all on Firefox either ...

**Comment by cullub** [comment] 2016-02-19 23:13
Huh.  Still working for me.  On Chrome, you need Taperminkey instead of Greasemonkey.

Supposedly [TrixIE will work in IE](http://stackoverflow.com/questions/25059256/possible-to-run-userscript-in-ie11), however I've not tried it.  You don't have to test it there if you don't want to - I forgot about having to install extra stuff.

**Comment by DavidPostill** [comment] 2016-02-19 23:15
I did install TamperMonkey ;)

**Comment by DavidPostill** [comment] 2016-02-19 23:46
I can't get SOX to work at all on IE with TrixIE WPF4.5

**Comment by cullub** [comment] 2016-02-20 00:06
Not a big deal.  Although IE is the biggest browser it terms of usage, it's generally the hardest to support, and I'm not too surprised it doesn't work.

**Comment by cullub** [comment] 2016-02-20 00:07
Is the bug still happening for you on FF windows?

**Comment by DavidPostill** [comment] 2016-02-20 09:23
"Is the bug still happening for you on FF windows?" - a different bug. I don't get the author's name at all regardless of whether ""Add the author's name to notifications in the inbox" is checked or not. Bizarre.

**Comment by DavidPostill** [comment] 2016-02-20 09:27
"Is the bug still happening for you on FF windows?" - a different bug. I don't get the author's name at all regardless of whether ""Add the author's name to notifications in the inbox" is checked or not. Bizarre. I wonder if it's clashing with another script? I have a bunch of SE scripts installed. SOUP being the main one.

**Comment by cullub** [comment] 2016-02-20 14:15
Try disabling other SE scripts, and see if you can reproduce - if it's being caused by different scripts, what we can do is probably pretty limited...

**Comment by DavidPostill** [comment] 2016-02-20 14:26
Ok. Cracked it. It only happens when SOUP is also enabled :/

**Comment by enki-code** [comment] 2016-02-20 16:36
Thanks for taking the time to work on this, I'll see what I can come up with and we will try to push some updates soon. @shu8  You have time to look into this today?

**Comment by DavidPostill** [comment] 2016-02-20 16:59
No problem and no rush. As far as I'm concerned the issue is cosmetic and not a show stopper. Hi @shu8 ;)

**Comment by shu8** [comment] 2016-02-20 18:51
I'm away today. I'll fix this tomorrow or Monday @enki. Though i have a
feeling you're getting throttled by SE api @DavidPostill. Not sure cause I
don't have a computer to test on :/

**Comment by enki** [comment] 2016-02-21 04:25
I'm enki.. you mean @enki-code

**Comment by enki-code** [comment] 2016-02-21 05:55
@enki  So you're the guy who stole my handle. J/K LOL. Lucky bastard. I envy you my friend.

**Comment by shu8** [comment] 2016-02-21 13:15
@enki sorry! I was replying via email and thought it was enki.. :/

**Comment by shu8** [comment] 2016-02-21 15:35
@DavidPostill and @enki-code to summarise the last few messages...:

- names appear twice if you have SOUP enabled
- names stopped appearing because of SE API's throttling

am I right?

I'm just going to look at SOUP's source and see if I can spot anything that causes it to happen.. :)

**Comment by shu8** [comment] 2016-02-21 15:43
ok... this is due to fix `mse207526`:

```
fixes.mse207526 = {
	title:	"Cannot navigate into the multicollider with keyboard",
	url:	"http://meta.stackexchange.com/q/207526",
	script:	function () {
		if ( !window.StackExchange || !StackExchange.topbar ) return;
		SOUP.hookAjax( /^\/topbar\//, function () {
			$('.js-site-switcher-button').after($('.siteSwitcher-dialog'));
			$('.js-inbox-button').after($('.inbox-dialog'));
			$('.js-achievements-button').after($('.achievements-dialog'));
		} );
		// fix bug causing clicks on the site search box to close the menu
		// XXX: this would be a lot easier if jQuery bubbled middle/right clicks :-(
		var fixTopbarClickHandler = function () {
			var clickHandlers = $._data(document, 'events').click || [];
			clickHandlers.forEach( function (h) {
				if ( !/\$corral\b/.test( h.handler.toString() ) ) return;
				var oldHandler = h.handler;
				h.handler = function (e) {
					if ( $(e.target).closest('.topbar-dialog').length ) return;
					return oldHandler.apply(this, arguments);
				};
			} );
		};
		SOUP.try( 'topbar click handler fix', fixTopbarClickHandler );
		// XXX: on chat, this fix might run before the topbar is initialized
		var oldInit = StackExchange.topbar.init;
		StackExchange.topbar.init = function () {
			oldInit.apply(this, arguments);
			SOUP.try( 'topbar click handler fix (deferred)', fixTopbarClickHandler );
		};
	}
};
```

deleting that stops the names from appearing twice. But I don't know why it happens or how to fix it yet :/ any ideas @enki-code?

**Comment by DavidPostill** [comment] 2016-02-21 16:45
Hi @shu8 The names appearing twice with SOUP enabled is correct. I don't know why the stop appearing but API throttling sounds likely

**Comment by shu8** [comment] 2016-02-21 16:46
@DavidPostill yeah probably because you were trying loads of times in a short period of time I assume?

**Comment by DavidPostill** [comment] 2016-02-21 16:50
@shu8 Yes probably. @enki-code asked me to test on Chrome and IE, so I was pulling down the inbox on 3 different browsers :/

**Comment by enki-code** [comment] 2016-02-28 16:36
@DavidPostill Is this still an issue for you?

**Comment by DavidPostill** [comment] 2016-02-28 17:16
@enki-code Yes, it is.

**Comment by shu8** [comment] 2016-02-28 17:43
@enki-code it's due to [this SOUP code](https://github.com/soscripted/sox/issues/7#issuecomment-186846282). but tbh I don't really get it :/

**Comment by enki-code** [comment] 2016-02-29 02:23
@shu8 Can we add a check to see if the authors name has already been added?

**Comment by shu8** [comment] 2016-02-29 17:53
@enki-code good point. I'll do that when I get some spare time (tomorrow/thursday) :)

**Comment by enki-code** [comment] 2016-02-29 18:17
@shu8 We should probably just do a check and see if SOUP is enabled, and then process accordingly, I doubt this will be the only feature overlap that could cause us issues. I'll fiddle with this a bit today and see what I come up with.

**Comment by shu8** [comment] 2016-03-05 11:45
@enki-code I don't get what SOUP's doing! It's adding the extra author name *before* the first one is even added! See, if I add a `<span>` around the author name, I get:

![this](https://cloud.githubusercontent.com/assets/8850830/13547357/a3440b8a-e2c7-11e5-851b-49fe427dd2a1.png)

the span is *after* the first name, which means SOUP is doing something weird :P 

I don't know how to fix this... :(

**Comment by enki-code** [comment] 2016-03-05 16:43
Since all fixes are applied automatically with SOUP, we could just check is SOUP is running and if so NOT apply our fix.?

**Comment by DavidPostill** [comment] 2016-03-05 16:58
Sounds like it might work ;)

-- 
David Postill

**Comment by enki-code** [comment] 2016-03-05 17:37
@DavidPostill  Sorry this is taking so long..

**Comment by shu8** [comment] 2016-03-05 17:37
@enki-code I can't even read window.SOUP from the code...

**Comment by DavidPostill** [comment] 2016-03-05 17:45
@enki-code Like I said earlier in the thread "No problem and no rush. As far as I'm concerned the issue is cosmetic and not a show stopper. "

**Comment by enki-code** [comment] 2016-03-05 21:42
@DavidPostill This should be resolved, changes have been pushed to the dev branch and should be merged shortly.

**Closed** 2016-03-05 21:41 UTC
Labels: compatibility
