### ISSUE TITLE
For features that have their own settings, the feature after it is disabled on refresh

### ISSUE THREAD

**Issue by Sir-Cumference** [soscripted/sox#274] opened 2017-03-23 16:38 UTC
### Installed Version: 2.0.24  Environment: Tampermonkey

If you already have "Add how many reviews are available on Meta to the main site review page" enabled, make any changes to your settings, and click "Save Changes", the checkbox for the Meta reviews will disappear:

<img width="547" alt="screen shot 2017-03-23 at 12 34 46 pm" src="https://cloud.githubusercontent.com/assets/5375326/24258763/232fdbbe-0fc5-11e7-8925-22300a2225fe.png">

It will reappear when you reload the page. The option will also disappear if you enable "Add how many reviews are available on Meta to the main site review page" and click "Save Changes"; it will reappear when you reload the page.

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-metaNewQuestionAlert","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Editing-downvotedPostsEditAlert","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-linkedToFrom","Chat-replyToOwnChatMessages","Voting-betterCSS","Voting-grayOutVotes","Voting-disableOwnPostVoteButtons","Extras-alwaysShowImageUploadLinkBox","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-hideCertainQuestions","Extras-showMetaReviewCount"]

**Comment by shu8** [comment] 2017-03-30 18:54
Seems to be a problem with the per-feature settings -- it happens to "Change highlighting for questions with favourite tags" if you have "fixed topbar" enabled as well -- it looks like the feature underneath the one with the individual settings is deleted :/

Might take a while to find the cause of this! :( Thanks for raising the issue! :)

**Comment by shu8** [comment] 2017-04-06 18:12
@Sir-Cumference this *should* be fixed in [dev 2.0.28](https://github.com/soscripted/sox/raw/dev/sox.user.js) now :) Please could you confirm?

**Closed by shu8** 2017-04-06 18:12 UTC
Labels: bug, confirmed, in progress, ready

**Comment by Sir-Cumference** [comment] 2017-04-07 18:33
@shu8 Seems to work!

Also, did you see my post [here](https://github.com/soscripted/sox/issues/79)? :)
