### ISSUE TITLE
SBS layout broken with Find & Replace enabled

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#141] opened 2016-11-06 01:57 UTC
### Installed Version: 2.0.2 Dev P  Environment: Firefox/Greasemonkey 

---
###  Expected Behavior
Previously working correctly

---
### Actual Behavior
The "rendered" view (right side) is offset below the edit box when using SBS in the review queue (and only there).  This is an edit in the Close Votes Review queue:

![su sbs](https://cloud.githubusercontent.com/assets/10065766/20034806/eaef40a8-a3a1-11e6-8ec1-f8092915f431.png)

Another flaky behavior.  I went to capture console output.  I opened and cleared the console, refreshed the page, and it now looks like this:

![su sbs1](https://cloud.githubusercontent.com/assets/10065766/20034821/89bf939a-a3a2-11e6-9959-9b0b85c31142.png)

No sense adding console output.  I'll have to see if the problem repeats and try to figure out more details on the conditions/

OK Find&Replace is the culprit.  It was active when I originally turned on SBS.  When I refreshed the page for the console output, it returned to the normal view.  I turned on SBS and it appeared normal (2nd picture).  When I started to use Find&Replace again, the right side shifted down.

---
### SOX Errors logged to the browser console (if available)

Let me know if console output is needed, or if the information is enough to ID the issue.
```

```

---

**Comment by fixer1234** [comment] 2016-11-06 02:20
I spoke to soon about the SBS issue occurring only in the review queue.  It looks like a general problem with the edit menu add-ons everywhere, it just manifests differently in the review queue.  I couldn't go back and revise the title.  When I checked other locations for the problem  earlier, I just looked quickly to see if SBS looked normal, and that was before discovering the Find&Replace connection.

I picked a random post (a question), and opened the edit window.  Two issues: Find&Replace|Autocorrect don't display, and SBS doesn't toggle.  It opens SBS, but doesn't toggle off.

![su sbs2](https://cloud.githubusercontent.com/assets/10065766/20034884/984620c0-a3a5-11e6-945a-a34b9c36da21.png)

```
The connection to wss://qa.sockets.stackexchange.com/ was interrupted while the page was loading. full.en.js:1:6864
The connection to ws://qa.sockets.stackexchange.com/ was interrupted while the page was loading. sox.features.js:1652:20
GET 
http://superuser.com/posts/325741/edit [HTTP/1.1 200 OK 35ms]
GET 
http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js [HTTP/1.1 304 Not Modified 28ms]
GET 
http://cdn.sstatic.net/Js/stub.en.js [HTTP/1.1 304 Not Modified 31ms]
GET 
http://cdn.sstatic.net/Sites/superuser/all.css [HTTP/1.1 304 Not Modified 32ms]
TypeError: can't access dead object jquery-2.1.4.min.js:2:30322
TypeError: can't access dead object jquery-2.1.4.min.js:2:30322
GET 
https://i.stack.imgur.com/DPd3M.jpg [HTTP/1.1 304 Not Modified 19ms]
GET 
https://www.google-analytics.com/analytics.js [HTTP/2.0 304 Not Modified 13ms]
GET 
http://edge.quantserve.com/quant.js [HTTP/1.1 304 Not Modified 29ms]
GET 
http://b.scorecardresearch.com/beacon.js [HTTP/1.1 200 OK 31ms]
GET 
http://cdn.sstatic.net/img/share-sprite-new.svg [HTTP/1.1 304 Not Modified 22ms]
GET 
http://cdn.sstatic.net/Sites/superuser/img/sprites.svg [HTTP/1.1 304 Not Modified 18ms]
SOX:  undefined sox.common.js:8:13
SOX:  Object { init: StackExchange.init</<(o, s), debug: Object, initialized: Object, ready: StackExchange.ready(e), using: v(e, n, i, a), ifUsing: b(e, t, n), loadJsFile: StackExchange.loadJsFile(e, t), loadJqueryUi: StackExchange.loadJqueryUi(), helpers: Object, switchMobile: StackExchange.switchMobile(e), 5 more… } sox.common.js:8:13
GET 
http://b.scorecardresearch.com/b [HTTP/1.1 204 No Content 20ms]
GET 
http://cdn.sstatic.net/Js/full.en.js [HTTP/1.1 304 Not Modified 18ms]
GET 
http://cdn.sstatic.net/Js/tageditornew.en.js [HTTP/1.1 304 Not Modified 16ms]
XrayWrapper denied access to property "ready" (reason: value is callable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported. sox.common.js:65:0
GET 
https://www.google-analytics.com/collect [HTTP/2.0 200 OK 12ms]
GET 
http://pixel.quantserve.com/pixel;r=273806783;a=p-c1rF4kxgLUzNc;fpan=0;fpa=P0-2087723673-1465952398859;ns=0;ce=1;cm=;je=1;sr=2048x1152x24;enc=n;dst=1;et=1478398671985;tzo=240;ref=http%3A%2F%2Fsuperuser.com%2Fquestions%2F325741%2Fwhy-do-add-ons-become-incompatible-when-upgrading-firefox;url=http%3A%2F%2Fsuperuser.com%2Fposts%2F325741%2Fedit;ogl=type.website%2Cimage.http%3A%2F%2Fcdn%252Esstatic%252Enet%2FSites%2Fsuperuser%2Fimg%2Fapple-touch-icon%402%252Epng%3Fv%3De869e4459439%2Ctitle.Edit%2Cdescription.Q%26A%20for%20computer%20enthusiasts%20and%20power%20users%2Curl.http%3A%2F%2Fsuperuser%252Ecom%2Fposts%2F325741%2Fedit [HTTP/1.1 200 OK 30ms]
GET 
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css [HTTP/2.0 304 Not Modified 15ms]
SOX:  initializing SOX dialog sox.common.js:32:13
SOX:  injecting features into dialog sox.common.js:32:13
SOX:  running addAuthorNameToInboxNotifications sox.common.js:8:13
SOX:  observe: .inbox-dialog sox.common.js:8:13
SOX:  undefined sox.common.js:8:13
SOX:  running addEllipsis sox.common.js:8:13
SOX:  running fixedTopbar sox.common.js:8:13
SOX:  running hideHireMe sox.common.js:8:13
SOX:  running markEmployees sox.common.js:8:13
SOX:  SOX Access Token: SET sox.common.js:8:13
SOX:  running metaChatBlogStackExchangeButton sox.common.js:8:13
SOX:  running metaNewQuestionAlert sox.common.js:8:13
SOX:  running scrollToTop sox.common.js:8:13
SOX:  running standOutDupeCloseMigrated sox.common.js:8:13
SOX:  running addSBSBtn sox.common.js:8:13
SOX:  observe: li[id^="wmd-redo-button"] sox.common.js:8:13
SOX:  undefined sox.common.js:8:13
SOX:  running editComment sox.common.js:8:13
SOX:  running kbdAndBullets sox.common.js:8:13
SOX:  observe: [id^="wmd-redo-button"] sox.common.js:8:13
SOX:  undefined sox.common.js:8:13
SOX:  running flagOutcomeTime sox.common.js:8:13
SOX:  running flagPercentages sox.common.js:8:13
SOX:  running downvotedPostsEditAlert sox.common.js:8:13
SOX:  Object {  } sox.common.js:8:13
SOX:  Object {  } sox.common.js:8:13
SOX:  running warnNotLoggedIn sox.common.js:8:13
GET 
XHR 
https://api.stackexchange.com/2.2/users/ [HTTP/1.1 200 OK 128ms]
GET 
XHR 
https://api.stackexchange.com/2.2/questions [HTTP/1.1 400 Bad Request 61ms]
GET 
https://rawgit.com/shu8/SE-Answers_scripts/master/dupeClosedMigratedCSS.css [HTTP/2.0 304 Not Modified 37ms]
```

All the code posted above is from refreshing the page.  Clicking the SBS button didn't generate any additional console output.

**Comment by shu8** [comment] 2016-11-13 14:53
@fixer1234 just to clarify then... the problem is that when find&replace is active, SBS gets all screwed up? (which I *can* repro, working on a fix now).

Is there another issue?

**Comment by shu8** [comment] 2016-11-13 18:17
@fixer1234 the SBS/find&replace issue is fixed in latest [dev version q](https://github.com/soscripted/sox/raw/dev/sox.user.js). Please do comment if there's another issue here.

**Closed by shu8** 2016-11-13 18:17 UTC
Labels: bug, confirmed, in progress, ready

**Comment by fixer1234** [comment] 2016-11-13 20:44
@shu8 Just did a quick random test and didn't see evidence of the problem.
