### ISSUE TITLE
SSOX dialog displaced to left of screen when Post Ids Everywhere user script is installed

### ISSUE THREAD

**Issue by DavidPostill** [soscripted/sox#387] opened 2019-03-28 23:12 UTC
To repro install https://github.com/samliew/SO-mod-userscripts/blob/master/PostIdsEverywhere.user.js then click on SOX top bar icon

![Screenshot - 28_03_2019 , 23_09_37](https://user-images.githubusercontent.com/7079224/55198743-2dbd0600-51af-11e9-9c9a-e603993ac000.png)

**Comment by shu8** [comment] 2019-03-29 09:08
Thanks for the bug report @DavidPostill!

I think this is a duplicate of #385, please could you see if that change fixes it for you?

**Comment by DavidPostill** [comment] 2019-03-29 09:48
Yeah. That fixed it. Thanks.

**Closed** 2019-03-29 10:08 UTC
Labels: bug, compatibility
