### ISSUE TITLE
Blog links not working

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#104] opened 2016-08-30 20:28 UTC
### Installed Version: 1.X.X  Environment: Chrome/Tampermonkey 
2.0.1G
...

###  Expected Behavior
When I go to the menu and hover over a site, a blog link will appear. That link will take me to the blog for the site.
...

### Actual Behavior
Two problems:
1) The blog link appears, but it pretty much only takes me to blog.stackexchange.com, instead of the specific blog for the site.

2) Mathematics seems to work, but introduces a second problem. If I hover over the blog button for the Mathematics SE, and then click on the link to another site's blog, it will direct me to math.blogoverflow.com.
...

### SOX Errors logged to the browser console (if available)

...

### Steps to reproduce
First problem:
1. Open the Stack Exchange menu (top-left)
2. Click on any of the links to the blogs, and notice that you are taken to the StackOverflow blog.

Second problem:
1. Open the Stack Exchange menu (top-left)
2. Hover over the blog link for Mathematics SE, but do not click on it
3. Click on the blog links for any other site, and notice that you are taken to Math SE's blog.

**Comment by shu8** [comment] 2016-08-30 20:29
Hi again! Thanks for posting this bug! I remember coming across this bug a while back and completely forgot about it. I have (re-)reproduced this. Hopefully, this will be fixed by v2.0.2 at the latest. I'll keep you posted on the progress of the fix :)

**Comment by shu8** [comment] 2016-10-01 13:58
@IStoleThePies Sorry for such a long wait, but this should be fixed now in [v2.0.1m](https://github.com/soscripted/sox/raw/fix/sox.user.js) -- the issue was that not all sites have blogs, so the script made the URL for any sites which did have a blog, but never changed the variable if they didn't, so it stuck with any non-blog sites :/

Please could you try installing it [from this link](https://github.com/soscripted/sox/raw/fix/sox.user.js) and confirm it is working (or not)? :) Thanks!

**Comment by IStoleThePies** [comment] 2016-10-01 14:05
The chat links work perfectly, but the blog links are still very glitchy.
Sometimes they might just send me to my profile page on that site; other
times they may send me to completely different SE sites.

I'd also like to mention that blogs were discontinued a few years ago. The
sites that made blogs before they were discontinued can still update them,
but almost all SE sites don't have blogs, nor can they make them.

**Comment by shu8** [comment] 2016-10-01 16:49
@IStoleThePies hmm, I was totally unaware that sites could no longer make new blogs!

TBH that kind of makes me think how useful the blog link really is, if it will only *ever* work on 20-or-odd sites, most of which haven't had new posts in quite a while.

Quick question: have you ever used the blog link? (I'm thinking of just getting rid of the blog link and keeping the chat one...)

**Comment by IStoleThePies** [comment] 2016-10-01 16:54
@shu8 To be honest, I was never active on a site that used blogs. I had only learned about them from sox. That said, out of the 24 sites that use it, only five have actually updated in this past year, and only Science Fiction & Fantasy is regularly active (one new blog post per week). I'd probably vote on removing them, since they are almost abandoned.

**Comment by shu8** [comment] 2016-10-01 16:55
@IStoleThePies yep, looks like I'll just get rid of it -- it's easier for me :P

**Comment by shu8** [comment] 2016-10-01 18:33
Removed the blog link in [v2.0.1n](https://github.com/soscripted/sox/raw/fix/sox.user.js)

**Closed by shu8** 2016-10-01 18:33 UTC
Labels: bug, confirmed, ready
