### ISSUE TITLE
Tiny line left after hovering over code

### ISSUE THREAD

**Issue by Gloin1313** [soscripted/sox#261] opened 2017-02-19 16:00 UTC
### Current Behaviour
When the setting "Add a button to code in posts to let you copy it" is turned on, after removing your mouse from the box, the "copy" icon disappears, but a tiny horizontal line is left at the top of where it was.  I know the problem is _tiny_ but I thought I should report it.

---

### Steps to reproduce
Turn "Add a button to code in posts to let you copy it" on. Hover over a code section, then remove mouse. There will be a tiny horizontal line where the "copy" icon was.

**Comment by shu8** [comment] 2017-02-19 20:38
@Gloin1313 Please could you post a screenshot of this? I can't seem to reproduce it, and I've zoomed in a bit as well :/

**Comment by Gloin1313** [comment] 2017-02-19 20:41
![screenshot 2017-02-19 at 20 39 08](https://cloud.githubusercontent.com/assets/22625968/23106328/902510d6-f6e3-11e6-897e-a2fc48b9650f.png)
![screen shot 2017-02-19 at 20 39 16](https://cloud.githubusercontent.com/assets/22625968/23106330/9025497a-f6e3-11e6-9ba1-db320ca1d6a2.png)
![screen shot 2017-02-19 at 20 39 23](https://cloud.githubusercontent.com/assets/22625968/23106329/90252814-f6e3-11e6-9219-06e9c558ea39.png)

Before, during, after. Thanks

**Comment by shu8** [comment] 2017-02-19 20:43
hmmm that's very weird. It's gonna be pretty low down on my todo list, but I'll try and get it fixed *sometime*! :) (it is, after all, a bug :P)

**Comment by wgrundlingh** [comment] 2017-02-20 18:15
There is no problem within Chrome for this.

**Comment by shu8** [comment] 2017-02-20 19:08
@wgrundlingh yeah, that's what it seems, I was hoping to try it out on Safari to see if I could repro it, because it _looks_ like it should be an easy fix...

**Comment by shu8** [comment] 2017-03-30 19:18
@Gloin1313 I'm sorry, but I couldn't manage to reproduce this :(

As you said though, it's a relatively minor issue, so I'm going to close this, but I'll keep an eye out for that button from now on, just in case I ever spot it!

**Closed by shu8** 2017-03-30 19:18 UTC
Labels: bug

**Comment by Gloin1313** [comment] 2017-04-05 16:53
It appears to have stopped happening now anyway... only just noticed this! I'll let you know if I see it again, just so you know.
