### ISSUE TITLE
Edit features missing (SBS, KBD/List, and Find&Replace/Autocorrect)

### ISSUE THREAD

**Issue by fixer1234** [soscripted/sox#86] opened 2016-08-13 19:07 UTC
**Installed Version: 1.X.X  |  Environment: Chrome/Tampermonkey**
Note: Environment: Firefox, not Chrome

**Expected Behavior**
>How do you expect the feature to work?
The SBS, KBD/List, and Find&Replace/Autocorrect options should appear in the edit toolbar

**Actual Behavior**
>How is the feature currently behaving?
In the built-in answer area, only the Find&Replace/Autocorrect option appears.  In the manually opened edit window, none of the three appears.  See attached images.

**Error Logs**
>SOX errors are logged to the browser console, if possible, please post those here.

**Steps to reproduce**
>What steps did you take to reproduce the issue?
Opened the random first question on the main page.

Manual edit window:
![sox edit box](https://cloud.githubusercontent.com/assets/10065766/17645037/74360392-6167-11e6-9d7a-38cff47740c0.png)

Built-in answer box:
![sox answer box](https://cloud.githubusercontent.com/assets/10065766/17645038/83ed658c-6167-11e6-886f-35e51df1b7d3.png)

**Comment by shu8** [comment] 2016-08-13 21:18
Duplicate of #72

**Closed by shu8** 2016-08-13 21:18 UTC
