### ISSUE TITLE
Disable notifications on self-replies

### ISSUE THREAD

**Issue by IStoleThePies** [soscripted/sox#144] opened 2016-11-13 15:23 UTC
Every time I reply to myself in the chat, a notification pops up.

**Comment by IStoleThePies** [comment] 2016-11-20 08:10
@shu8 Also, I can't reply to my own posts if I'm hovering over my timestamp. On other posts, I can.

**Comment by shu8** [comment] 2016-11-20 15:45
@IStoleThePies fixed the timestamp bug in [dev y](https://github.com/soscripted/sox/raw/dev/sox.user.js) :)

**Comment by shu8** [comment] 2016-11-20 15:53
@IStoleThePies also, looking into this, I don't think it's actually possible for SOX to disable the notification, because we can only make new ones rather than stopping ones from being created... :/

I'll leave this open for a while and look into it, but I don't *think* we'll be able to add this feature :(

**Comment by IStoleThePies** [comment] 2016-11-20 23:43
@shu8 Uh, now when I hover over a time stamp, the flag/star/reply panel keeps flickering:

<img width="979" alt="screen shot 2016-11-20 at 6 41 57 pm" src="https://cloud.githubusercontent.com/assets/5375326/20467232/21ab85a6-af51-11e6-965d-962adf1e79b5.png">

**Comment by shu8** [comment] 2016-11-21 07:57
Weird.. I'll look into it on the weekend :)

**Comment by shu8** [comment] 2016-11-26 14:28
@IStoleThePies I can't seem to reproduce this... Could you upload a gif if possible? :)

**Comment by IStoleThePies** [comment] 2016-11-29 02:33
@shu8 Seems to be working now (sort of). By the way, I rewrote the reply button function to fix a lot of bugs:

    replyToOwnChatMessages: function() {
            //I use $(document).on instead of .each, since using .each wouldn't apply to messages loaded via "Load more messages" and "Load to my last message"

            $(document).on('mouseenter', '.mine .message', function() {
                //Remove excess spacing to the left of the button (by emptying .meta, which has "&nbsp" in it), and set the button color to the background color
                $(this).find('.meta').empty().css({"background-color": $(this).parent().css("background-color"), "padding-right": "1px"}).show().append(replySpan);
                //The "padding-right: 1px" is to avoid some weird bug I can't figure out how to fix
            }).on('mouseleave', '.mine .message', function() {
                $(this).find('.meta').hide().find('.newreply').remove();
            })

            //Do the same thing if you hover over the timestamp
            .on('mouseenter', '.mine .timestamp', function() {
                $(this).next().find('.meta').empty().css({"background-color": $(this).parent().css("background-color"), "padding-right": "1px"}).show().append(replySpan);
            }).on('mouseleave', '.mine .timestamp', function() {
                $(this).next().find('.meta').hide().find('.newreply').remove();
            })

            .on('click', '.newreply.added-by-sox', function(e) {
                var $message = $(e.target).closest('.message'),
                    id = $message.attr('id').split('-')[1],
                    rest = $('#input').focus().val().replace(/^:([0-9]+)\s+/, '');
                $('#input').val(':' + id + ' ' + rest).focus();
            });

            var replySpan = $('<span/>', {
                class: 'newreply added-by-sox',
                'title': 'link my next chat message as a reply to this'
            });
        },

This fixes the following bugs I found:

- The star count on my own messages didn't show next to the message (".stars" applies to both the message's meta icon and the stars next to the message. I decided to empty the meta altogether instead of hiding the buttons, which fixed this problem as well as another one)
- The background color of the reply button didn't match the color of the message (my code sets the button's color to that of its parent, which is the message)
- The reply button doesn't show up on older posts if you click "Load more messages" and "Load to my last message" (I chose to forgo .each in favor of adding the reply button whenever you hover over your own message)
- There's an excess left spacing on the reply button (caused by "&nbsp" in the meta. Emptying the meta resolved this)
- Moving your mouse over the reply button from right to left on the timestamp makes it flicker (seems like a manifestation of the problem I mentioned before. After messing around, the only fix I found was to add a right padding to the button, which shifts it a bit but removes the problem):

![untitled-2](https://cloud.githubusercontent.com/assets/5375326/20694268/fe4723ce-b5b1-11e6-9939-e6f59e5dec82.gif)

Tell me if you think it's all right or you need any clarification :)

**Comment by shu8** [comment] 2016-12-07 08:04
Thanks. It looks really good! I've added this in my local version and it'll be there in my next push on the weekend :)

I'll ping you when it's been released in dev

**Comment by shu8** [comment] 2016-12-10 17:47
@IStoleThePies I've pushed it now :) You can see it [in dev ad](https://github.com/soscripted/sox/raw/dev/sox.user.js). 

BTW, I just realised we've been talking about this on the wrong issue! :( Would it be possible for you to copy-paste [your comment](https://github.com/soscripted/sox/issues/144#issuecomment-263459197) as a new comment on #118? -- because I want to be able to link to the comment from the code as a credit but it's going to get confusing if I link to this issue, which is a different issue!

**Comment by shu8** [comment] 2016-12-12 21:04
@IStoleThePies I looked into this a bit more and I'm pretty certain that this just isn't possible as a userscript now -- it would require intercepting the notifications which isn't really possible AFAIK, so we're just going to have to close this issue :(

Sorry! But I'll keep this in my mind to see if I come across anything in the next few months that could help with this issue! :)

**Closed by shu8** 2016-12-12 21:04 UTC
Labels: feature request
