### ISSUE TITLE
Duplicated question voting buttons

### ISSUE THREAD

**Issue by wgrundlingh** [soscripted/sox#258] opened 2017-02-16 20:05 UTC
### Current Behaviour

I'm not entirely sure how to replicate this, since I haven't found a common cause. I visited some of my questions listed in the reputation tab of my profile, and clicked on them. Here I show me clicking around in Google Chrome:

![latex_stuff](https://cloud.githubusercontent.com/assets/1776164/23038302/61ab6a68-f43e-11e6-8b3b-68e27304379f.gif)

Some links that showed the voting button issue:
- http://tex.stackexchange.com/questions/354098/you-have-requested-document-class-x-but-the-document-class-provides-y-warning/354099#354099
- http://tex.stackexchange.com/questions/31780/where-can-i-find-help-files-or-documentation-for-commands-like-startsection-fo/31795#31795
- http://tex.stackexchange.com/questions/33377/aligning-plain-align-and-cases/33380#33380

---

### SOX Errors logged to the browser console -- F12 (if available)

```
[](SOX:  DEBUGGING SOX VERSION 2.0.22
VM2666:565 SOX:  ----------------saved variables---------------------
VM2666:589 SOX:  logging sox stored values --- 
VM2666:589 SOX:  access token set
VM2666:589 SOX:  SOXSETTINGS
VM2666:589 SOX:  ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar"]
VM2666:589 SOX:  editReasons
VM2666:589 SOX:  [["formatting","Improved Formatting"],["spelling","Corrected Spelling"],["grammar","Fixed grammar"],["greetings","Removed thanks/greetings"]]
VM2666:589 SOX:  metaNewQuestionAlert-lastQuestions
VM2666:589 SOX:  {"meta.tex":"Upcoming event &quot;Answer the unanswered&quot;"}
VM2666:589 SOX:  SOX-debug
VM2666:589 SOX:  true
VM2666:565 SOX:  ----------------end saved variables---------------------
VM2666:565 SOX:  initializing SOX dialog
VM2666:565 SOX:  injecting features into dialog
VM2666:565 SOX:  Object {name: "addAuthorNameToInboxNotifications", desc: "Add the author's name to notifications in the inbox", extended_description: "If you receive a comment/answer/suggested edit not…or of the comment/answer/edit to the notification", meta: "", match: ""…}
VM2666:565 SOX:  running addAuthorNameToInboxNotifications
VM2666:565 SOX:  observe: .inbox-dialog
VM2666:565 SOX:  Object {name: "alignBadgesByClass", desc: "Align badges by their class on user profile pages", meta: "http://meta.stackexchange.com/q/254607/260841", match: "*://*/users/*", exclude: "SE1.0"}
VM2666:565 SOX:  Object {name: "answerTagsSearch", desc: "Show tags for the question an answer belongs to on search pages (for better context)", extended_description: "By default, any search results thar are answers do…e adds the question's tags underneath the result.", meta: "http://meta.stackexchange.com/questions/197874/include-tags-in-answers-entries-on-search-results", match: "*://*.com/search*"…}
VM2666:565 SOX:  Object {name: "colorAnswerer", desc: "Color answerer's comments", extended_description: "Highlight the username of a commenter if they have posted an answer on that page.", meta: "http://meta.stackexchange.com/questions/19574/high…from-answer-author-in-addition-to-question-author", match: "*://*/questions*"…}
VM2666:565 SOX:  running colorAnswerer
VM2666:565 SOX:  Object {name: "dragBounty", desc: "Make bounty box draggable", meta: "http://meta.stackexchange.com/questions/170125/make-bounty-custom-message-dialog-box-draggable", match: "*://*/questions*", exclude: "SE1.0"}
VM2666:565 SOX:  running dragBounty
VM2666:565 SOX:  observe: #start-bounty-popup
VM2666:565 SOX:  Object {name: "fixedTopbar", desc: "Fix topbar position", extended_description: "Locks the topbar to the top of the window so you c…e to the different default styling of the topbar.", meta: "http://meta.stackexchange.com/questions/101385/should-the-top-navigation-be-frozen-optional", match: ""…}
VM2666:565 SOX:  running fixedTopbar
VM2666:565 SOX:  observe: #notify-container,#notify--1
VM2666:565 SOX:  Object {name: "isQuestionHot", desc: "Add a label on questions which are hot-network questions", extended_description: "If the question you are currently viewing is HOT, a flame icon is added next to the title", meta: "http://meta.stackexchange.com/questions/245390/let-mods-and-10k-know-when-questions-go-hot", match: ""…}
VM2666:565 SOX:  running isQuestionHot
VM2666:565 SOX:  Object {name: "markEmployees", desc: "Add the SO logo after employee names to make them stand out", meta: "http://meta.stackexchange.com/questions/246678/sho…staff-have-a-special-character-in-their-user-name", match: "", exclude: "*://chat.*.com/*,SE1.0"}
VM2666:565 SOX:  running markEmployees
VM2666:565 SOX:  SOX Access Token: SET
VM2666:565 SOX:  Object {name: "metaChatBlogStackExchangeButton", desc: "Show meta and chat buttons on hover of a site under the StackExchange button", meta: "http://meta.stackexchange.com/questions/256183/sho…-and-blog-in-the-top-bar-for-other-sites-on-hover", match: "", exclude: ""}
VM2666:565 SOX:  running metaChatBlogStackExchangeButton
VM2666:565 SOX:  Object {name: "scrollToTop", desc: "Add Scroll To Top button", extended_description: "This feature adds a 'scroll to top' button at the …hat will jump to the top of the page when clicked", meta: "", match: ""…}
VM2666:565 SOX:  running scrollToTop
VM2666:565 SOX:  Object {name: "spoilerTip", desc: "Differentiate spoilers from empty blockquotes", meta: "http://meta.stackexchange.com/questions/104085/differentiate-spoilers-from-empty-block-quotes", match: "*://*/questions*,*://*/review*", exclude: "SE1.0"}
VM2666:565 SOX:  running spoilerTip
VM2666:565 SOX:  Object {name: "standOutDupeCloseMigrated", desc: "Add highlighted tags to closed/on hold/duplicate/migrated questions on question lists", extended_description: "Adds a coloured box at the end of a title (that re… more easily tell what the state of a question is", meta: "http://meta.stackexchange.com/questions/257021/pro…ate-closed-and-migrated-in-the-title-more-obvious", match: ""…}
VM2666:565 SOX:  running standOutDupeCloseMigrated
VM2666:565 SOX:  observe: #user-tab-questions, #question-mini-list
VM2666:565 SOX:  Object {name: "tabularReviewerStats", desc: "Display reviewer stats on /review/suggested-edits in table form", meta: "http://meta.stackexchange.com/q/276946/260841", match: "*://*.com/review/suggested-edits/*", exclude: ""}
VM2666:565 SOX:  Object {name: "topAnswers", desc: "Improve answer visibility by listing top answers", meta: "", match: "*://*/questions*", exclude: "SE1.0"}
VM2666:565 SOX:  running topAnswers
VM2666:565 SOX:  Object {name: "unspoil", desc: "Add a link to the bottom of a post to reveal all spoilers in a post", meta: "http://meta.stackexchange.com/questions/249808/add…ay-to-reveal-all-spoiler-blocks-in-a-post-at-once", match: "*://*/questions*", exclude: "SE1.0"}
VM2666:565 SOX:  running unspoil
VM2666:565 SOX:  Object {name: "autoShowCommentImages", desc: "View linked images (to imgur) in comments inline", extended_description: "This feature will automatically detect comments with links to imgur and will display them inline", meta: "", match: "*://*/questions*,*://*/review*"…}
VM2666:565 SOX:  running autoShowCommentImages
VM2666:565 SOX:  Object {name: "commentReplies", desc: "Add reply links to comments for quick replying (without having to type someone's username)", meta: "http://meta.stackexchange.com/questions/74778/add-…ment-that-pre-populates-comment-box-with-username", match: "*://*/questions*,*://*/review*", exclude: "SE1.0"}
VM2666:565 SOX:  running commentReplies
VM2666:565 SOX:  Object {name: "commentShortcuts", desc: "Use Ctrl+I,B,K (to italicise, bolden and add code backticks) in comments", meta: "http://meta.stackexchange.com/questions/14756/formatting-keyboard-shortcuts-for-comments", match: "*://*/questions*", exclude: "SE1.0"}
VM2666:565 SOX:  running commentShortcuts
VM2666:565 SOX:  Object {name: "confirmNavigateAway", desc: "Add a confirmation dialog when navigating away on pages whilst still typing a comment", meta: "http://meta.stackexchange.com/questions/252205/add…-navigate-away-from-this-page-when-writing-a-comm", match: "*://*/questions*", exclude: "SE1.0"}
VM2666:565 SOX:  running confirmNavigateAway
VM2666:565 SOX:  Object {name: "copyCommentsLink", desc: "Copy 'show x more comments' link to the top", meta: "http://meta.stackexchange.com/questions/55020/add-…-comments-button-to-the-top-of-a-list-of-comments", match: "*://*/questions*", exclude: "SE1.0"}
VM2666:565 SOX:  running copyCommentsLink
VM2666:565 SOX:  Object {name: "moveBounty", desc: "Move the 'start a bounty' link to before the comments", meta: "http://meta.stackexchange.com/questions/234095/can…-move-start-a-bounty-to-a-more-intuitive-location", match: "*://*/questions*", exclude: "SE1.0"}
VM2666:565 SOX:  running moveBounty
VM2666:565 SOX:  Object {name: "showCommentScores", desc: "Show your comment and comment replies scores in your profile tabs", extended_description: "Adds a button next to comments in your profile's r… when clicked, show you the score of your comment", meta: "http://meta.stackexchange.com/questions/38285/disp…umber-of-comment-upvotes-in-recent-activity-pages", match: "*://*/users/*"…}
VM2666:565 SOX:  Object {name: "hiddenCommentsIndicator", desc: "Add a darker border underneath comments if there are some hidden after it", meta: "http://meta.stackoverflow.com/q/296582/3541881", match: "*://*/questions*,*://*/review*", exclude: "SE1.0"}
VM2666:565 SOX:  running hiddenCommentsIndicator
VM2666:565 SOX:  Object {name: "addSBSBtn", desc: "Add a button to the editor toolbar to start side-by-side editing", extended_description: "An 'SBS' button is added to the right of the markd… the markdown and the preview appear side-by-side", meta: "http://meta.stackexchange.com/questions/253112/the…iscourse-layout-for-side-by-side-markdown-preview", match: ""…}
VM2666:565 SOX:  running addSBSBtn
VM2666:565 SOX:  observe: #wmd-redo-button-354099
VM2666:565 SOX:  observe: #wmd-redo-button-354141
VM2666:565 SOX:  observe: #wmd-redo-button-354098
VM2666:565 SOX:  observe: .wmd-preview.sbs-on
VM2666:565 SOX:  Object {name: "editComment", desc: "Pre-defined edit comment options (checkboxes)", extended_description: "Adds checkboxes to add canned messages for edit re… is added to the Help dropdown menu in the topbar", meta: "http://meta.stackexchange.com/questions/190461/imp…ing-flow-with-predefined-options-for-edit-summary", match: ""…}
VM2666:565 SOX:  running editComment
VM2666:565 SOX:  Object {name: "editReasonTooltip", desc: "Add a tooltip to posts showing the last revision's…on the word 'edited' in 'edited [date] at [time]'", extended_description: "When a post is edited, the editor is displayed und…d' underneath a post in 'edited [date] at [time]'", meta: "http://meta.stackexchange.com/questions/2315/show-reason-for-edit-without-clicking-through-to-diff", match: "*://*/questions*,*://*/review*"…}
VM2666:565 SOX:  running editReasonTooltip
VM2666:565 SOX:  Object {name: "enhancedEditor", desc: "Add more features to the markdown editor", extended_description: "Adds find/replace, changes the TAB key behaviour, …kGo integration, and basic auto-correct features.", meta: "", match: "*://*/questions*,*://*/review*"…}
VM2666:565 SOX:  running enhancedEditor
VM2666:565 SOX:  Object {name: "kbdAndBullets", desc: "Add KBD and list buttons to editor toolbar", extended_description: "Adds a kbd and bullet icon to the markdown editor … with KBD tags or listify's the current selection", meta: "http://meta.stackexchange.com/questions/102841/key-equivalent-for-kbd-kbd", match: "*://*/questions*,*://*/review*"…}
VM2666:565 SOX:  running kbdAndBullets
VM2666:565 SOX:  Object {name: "titleEditDiff", desc: "Make title edits show separately rather than merged in edit suggestions", meta: "http://meta.stackexchange.com/questions/135710/please-show-changed-titles-separately-in-edit-diffs", match: "*://*.com/review/suggested-edits*", exclude: ""}
VM2666:565 SOX:  Object {name: "inlineEditorEverywhere", desc: "Inline editor regardless of reputation", extended_description: "Enables the inline editor on all sites, even if yo… yet. Note: this feature may not work on Firefox.", meta: "", match: "*://*/questions*"…}
VM2666:565 SOX:  running inlineEditorEverywhere
VM2666:565 SOX:  Object {name: "flagOutcomeTime", desc: "Show the flag outcome time when viewing your Flag History", meta: "", match: "", exclude: "*://chat.*.com/*,SE1.0"}
VM2666:565 SOX:  running flagOutcomeTime
VM2666:565 SOX:  Object {name: "flagPercentages", desc: "Show flagging percentages for each type in the Flag Summary", meta: "", match: "", exclude: "*://chat.*.com/*,SE1.0"}
VM2666:565 SOX:  running flagPercentages
VM2666:565 SOX:  Object {name: "flagPercentageBar", desc: "Show the total percentage of helpful flags as a coloured bar on the Flag Summary Page", meta: "http://meta.stackoverflow.com/questions/310881/overall-percentage-of-helpful-flags", match: "", exclude: "*://chat.*.com/*,SE1.0"}
VM2666:565 SOX:  running flagPercentageBar
VM2666:565 SOX:  Object {name: "hideHireMe", desc: "Hide the Looking for a Job module", meta: "", match: "", exclude: "*://chat.*.com/*"}
VM2666:565 SOX:  running hideHireMe
VM2666:565 SOX:  Object {name: "hideHotNetworkQuestions", desc: "Hide the Hot Network Questions module", meta: "", match: "", exclude: "*://chat.*.com/*"}
VM2666:565 SOX:  running hideHotNetworkQuestions
VM2666:565 SOX:  Object {name: "linkedToFrom", desc: "Add an arrow to linked posts in the sidebar to show whether they are linked to or linked from", meta: "http://meta.stackexchange.com/q/276235/260841", match: "*://*/questions*", exclude: "SE1.0"}
VM2666:565 SOX:  running linkedToFrom
VM2666:565 SOX:  Object {name: "chatEasyAccess", desc: "Add buttons to user profiles to change user write access directly from a chat room", meta: "http://meta.stackexchange.com/q/203480/260841", match: "*://chat.*.com/*", exclude: ""}
VM2666:565 SOX:  Object {name: "replyToOwnChatMessages", desc: "Add reply signs to your own chat messages", meta: "", match: "*://chat.*.com/*", exclude: ""}
VM2666:565 SOX:  Object {name: "renameChat", desc: "Prepend 'Chat - ' to chat tabs' titles", meta: "http://meta.stackexchange.com/questions/246289/cha…-on-chat-pages-to-chat-sitename-or-chat-room-name", match: "*://chat.*.com/*", exclude: ""}
VM2666:565 SOX:  Object {name: "betterCSS", desc: "Add extra CSS for animation actions on voting and favourite buttons", extended_description: "Pulse effect when hovering over the upvote/downvot…urrently only implemented natively on Android.SE.", meta: "http://meta.stackexchange.com/questions/252685/i-w…oting-animations-like-on-android-se-pretty-please", match: "*://*/questions*,*://*/review*"…}
VM2666:565 SOX:  running betterCSS
VM2666:565 SOX:  Object {name: "grayOutVotes", desc: "Gray out deleted vote buttons", meta: "http://meta.stackexchange.com/a/174806/260841", match: "*://*/questions*", exclude: "SE1.0"}
VM2666:565 SOX:  running grayOutVotes
VM2666:565 SOX:  Object {name: "stickyVoteButtons", desc: "Make vote buttons next to posts sticky whilst scrolling on that post", meta: "http://meta.stackexchange.com/a/35047/260841", match: "*://*/questions*,*://*/review*", exclude: "SE1.0"}
VM2666:565 SOX:  running stickyVoteButtons
VM2666:565 SOX:  Object {name: "disableOwnPostVoteButtons", desc: "Disable vote buttons on your own posts", meta: "", match: "*://*/questions*", exclude: "SE1.0"}
VM2666:565 SOX:  running disableOwnPostVoteButtons
VM2666:565 SOX:  Object {name: "linkedPostsInline", desc: "Display linked posts inline by clicking on an arrow", extended_description: "Adds a button next to links to posts on the same site that expand to show the post inline", meta: "", match: "*://*/questions*,*://*/review*"…}
VM2666:565 SOX:  running linkedPostsInline
VM2666:565 SOX:  Object {name: "parseCrossSiteLinks", desc: "Parse titles to links cross-SE-sites", extended_description: "Detects links to other questions on SE sites and converts them to their title", meta: "http://meta.stackexchange.com/questions/251183/parse-question-links-from-other-se-sites", match: "*://*/questions*,*://*/review*"…}
VM2666:565 SOX:  running parseCrossSiteLinks
VM2666:565 SOX:  Object {name: "quickAuthorInfo", desc: "Show when the post's author was last seen and whether they are registered", meta: "", match: "*://*/questions*,*://*/review*", exclude: "SE1.0"}
VM2666:565 SOX:  running quickAuthorInfo
VM2666:565 SOX:  observe: .review-content
VM2666:565 SOX:  SOX Access Token: SET
VM2666:565 SOX:  Getting From API with URL: https://api.stackexchange.com/2.2/users/5764;93219;354141?order=desc&sort=c…&site=tex&key=lL1S1jr2m*DRwOvXMPp26g((&access_token=fvnIgs5zaMv*5bZnfvn09w))
VM2666:565 SOX:  SOX Access Token: SET
VM2666:8 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ VM2666:8
ajax @ VM2666:8
getFromAPI @ VM2666:670
getIdsAndAddDetails @ VM2666:3528
quickAuthorInfo @ VM2666:3553
init @ VM2666:4311
(anonymous) @ VM2666:622
j @ VM2666:6
fireWith @ VM2666:6
ready @ VM2666:6
I @ VM2666:6
(anonymous) @ VM2645:2
b @ VM2645:2
F @ VM2650:45
VM2666:565 SOX:  quickAuthorInfo api dump
VM2666:565 SOX:  Object {items: Array[2], has_more: false, quota_max: 10000, quota_remaining: 9697}
VM2666:565 SOX:  quickAuthorInfo userdetailsfromapi
VM2666:565 SOX:  Object {5764: Object, 93219: Object}
VM2666:565 SOX:  current post
VM2666:565 SOX:  [div#question.question, context: div#question.question]
VM2666:565 SOX:  quickAuthorInfo addLastSeen(): current id
VM2666:565 SOX:  93219
VM2666:565 SOX:  quickAuthorInfo addLastSeen(): userdetailscurrent id
VM2666:565 SOX:  Object {last_seen: 1487269289000, type: "registered"}
VM2666:565 SOX:  current post
VM2666:565 SOX:  [div#answer-354099.answer.accepted-answer, context: div#answer-354099.answer.accepted-answer]
VM2666:565 SOX:  quickAuthorInfo addLastSeen(): current id
VM2666:565 SOX:  5764
VM2666:565 SOX:  quickAuthorInfo addLastSeen(): userdetailscurrent id
VM2666:565 SOX:  Object {last_seen: 1487274836000, type: "registered"}
VM2666:565 SOX:  current post
VM2666:565 SOX:  [div#answer-354141.answer, context: div#answer-354141.answer]
VM2666:565 SOX:  quickAuthorInfo addLastSeen(): current id
VM2666:565 SOX:  354141
VM2666:565 SOX:  quickAuthorInfo addLastSeen(): userdetailscurrent id
VM2666:565 SOX:  undefined
VM2666:565 SOX:  quickAuthorInfo answerer IDs
VM2666:565 SOX:  Object {5764: "Werner", 93219: "Woeitg", 354141: "↵        Johannes_B↵        "}
VM2666:565 SOX:  quickAuthorInfo API call parameters
VM2666:565 SOX:  users
VM2666:565 SOX:  5764;93219;354141
VM2666:565 SOX:  tex
VM2666:565 SOX:  Object {name: "shareLinksMarkdown", desc: "Change 'share' link to format of [post-name](url)", extended_description: "When you click 'share' under a post, this will con…lly copies the converted string to your clipboard", meta: "http://meta.stackexchange.com/questions/126544/add…nd-share-button-to-posts-with-comment-ready-links", match: "*://*/questions*,*://*/review*"…}
VM2666:565 SOX:  running shareLinksMarkdown
VM2666:565 SOX:  observe: .share-tip
VM2666:565 SOX:  Object {name: "showMetaReviewCount", desc: "Add how many reviews are available on Meta to the main site review page", meta: "", match: "*://*/review", exclude: "*://meta.*.com/*"}
VM2666:565 SOX:  Object {name: "copyCode", desc: "Add a button to code in posts to let you copy it", meta: "", match: "*://*/questions*,*://*/review*", exclude: ""}
VM2666:565 SOX:  running copyCode
VM2666:565 SOX:  Object {name: "dailyReviewBar", desc: "Add a progress bar showing how many reviews you have left in the day", meta: "", match: "*://*/review*", exclude: ""}
VM2666:565 SOX:  observe: .new_comment
VM2666:565 SOX:  observe: li[id^="wmd-redo-button"], textarea[id^="wmd-input"]
VM2666:565 SOX:  observe: .reviewable-post, .review-content
VM2666:565 SOX:  SOX editReasonTooltip URL: http://tex.stackexchange.com/posts/354098/revisions
VM2666:565 SOX:  SOX editReasonTooltip text: edited tags
VM2666:565 SOX:  SOX editReasonTooltip: adding to tooltip
VM2666:565 SOX:  SOX editReasonTooltip: finished adding to tooltip
VM2666:565 SOX:  SOX editReasonTooltip: tooltip is now: edited tags
VM2666:565 SOX:  SOX editReasonTooltip URL: http://tex.stackexchange.com/posts/354099/revisions
VM2666:565 SOX:  SOX editReasonTooltip text: added 7 characters in body
VM2666:565 SOX:  SOX editReasonTooltip: adding to tooltip
VM2666:565 SOX:  SOX editReasonTooltip: finished adding to tooltip
VM2666:565 SOX:  SOX editReasonTooltip: tooltip is now: added 7 characters in body
VM2666:565 SOX:  SOX editReasonTooltip URL: http://tex.stackexchange.com/posts/354141/revisions
VM2666:565 SOX:  SOX editReasonTooltip text: 
VM2666:565 SOX:  SOX editReasonTooltip: adding to tooltip
VM2666:565 SOX:  SOX editReasonTooltip: finished adding to tooltip
VM2666:565 SOX:  SOX editReasonTooltip: tooltip is now: 
VM2666:565 SOX:  fixedtopbar adjust function running
VM2666:565 SOX:  fixedtopbar answer in hash and getBoundingClientRect
VM2666:565 SOX:  <div id=​"answer-354099" class=​"answer accepted-answer" data-answerid=​"354099" itemscope itemtype=​"http:​/​/​schema.org/​Answer" itemprop=​"acceptedAnswer" style=​"background-color:​ rgb(249, 211, 158)​;​">​…​</div>​
VM2666:565 SOX:  ClientRect {top: 43, right: 989.5, bottom: 1150, left: 261.5, width: 728…})
```

---

### Steps to reproduce

---

### Features Enabled 

    ["Appearance-addAuthorNameToInboxNotifications","Appearance-alignBadgesByClass","Appearance-answerTagsSearch","Appearance-colorAnswerer","Appearance-dragBounty","Appearance-fixedTopbar","Appearance-isQuestionHot","Appearance-markEmployees","Appearance-metaChatBlogStackExchangeButton","Appearance-scrollToTop","Appearance-spoilerTip","Appearance-standOutDupeCloseMigrated","Appearance-tabularReviewerStats","Appearance-topAnswers","Appearance-unspoil","Comments-autoShowCommentImages","Comments-commentReplies","Comments-commentShortcuts","Comments-confirmNavigateAway","Comments-copyCommentsLink","Comments-moveBounty","Comments-showCommentScores","Comments-hiddenCommentsIndicator","Editing-addSBSBtn","Editing-editComment","Editing-editReasonTooltip","Editing-enhancedEditor","Editing-kbdAndBullets","Editing-titleEditDiff","Editing-inlineEditorEverywhere","Flags-flagOutcomeTime","Flags-flagPercentages","Flags-flagPercentageBar","Sidebar-hideHireMe","Sidebar-hideHotNetworkQuestions","Sidebar-linkedToFrom","Chat-chatEasyAccess","Chat-replyToOwnChatMessages","Chat-renameChat","Voting-betterCSS","Voting-grayOutVotes","Voting-stickyVoteButtons","Voting-disableOwnPostVoteButtons","Extras-linkedPostsInline","Extras-parseCrossSiteLinks","Extras-quickAuthorInfo","Extras-shareLinksMarkdown","Extras-showMetaReviewCount","Extras-copyCode","Extras-dailyReviewBar"]

**Comment by shu8** [comment] 2017-02-16 20:14
Thanks, it looks like it might be a fixedtopbar issue... if it happens a lot, try disabling it and see if it still happens. I'll see if I can find a fix for this ASAP

**Comment by wgrundlingh** [comment] 2017-02-16 20:17
@shu8 Just tested without the fixed toolbar and the problem is still there.

**Comment by enki-code** [comment] 2017-02-17 17:06
From the screen capture you posted it looks like it's likely being caused by the topAnswers feature.

**Comment by wgrundlingh** [comment] 2017-02-17 23:59
@enki-code Just tested without the topAnswers feature and the result is similar.

**Comment by shu8** [comment] 2017-02-19 20:39
I just reproduced this and I don't have either enabled, so looks like the cause is something else.

I've added the confirmed label though, because it's definitely an issue.

**Comment by Sir-Cumference** [comment] 2017-02-21 16:35
I'll try to take a look at this soon.

**Comment by Sir-Cumference** [comment] 2017-02-22 21:44
Okay, I think I've found a fix:

    stickyVoteButtons: function() {
        // Description: For making the vote buttons stick to the screen as you scroll through a post
        //https://github.com/shu8/SE_OptionalFeatures/pull/14:
        //https://github.com/shu8/Stack-Overflow-Optional-Features/issues/28: Thanks @SnoringFrog for fixing this!

        stickcells();
        $(document).on('sox-new-review-post-appeared', stickcells);

        $(window).scroll(function() {
            stickcells();
        });

        function stickcells() {
            var $votecells = $('.votecell');
            $votecells.css('min-width', '46px');

            $votecells.each(function() {
                var $topbar = $('.topbar'),
                    topbarHeight = $topbar.outerHeight(),
                    offset = (sox.location.on('/review') ? 60 : 10);

                if ($topbar.css('position') == 'fixed') offset += topbarHeight;

                var $voteCell = $(this),
                    $vote = $voteCell.find('.vote'),
                    vcOfset = $voteCell.offset(),
                    scrollTop = $(window).scrollTop(),
                    realHeight, endPos;

                if (sox.location.on('/review/suggested-edits/')) $vote.css('padding-top', '35px');

                if ($vote.children().last().length && $vote.length && $voteCell.next().length) { //These values strangely alternate between existing and not existing. This if statement ensures we only get their values when they exist, so no errors.
                    realHeight = $vote.children(':not(:hidden, .message-dismissable)').last().offset().top + $vote.children(':not(:hidden, .message-dismissable)').last().height() - $vote.offset().top; //Get the original height; the difference between the last child and the first child's position
                    endPos = $voteCell.next().offset().top + $voteCell.next().height() - 51; //I think a bit above the end of the post (where the "edit", "delete", etc. buttons lie) is a good place to stop the stickiness.
                }

                if (realHeight + vcOfset.top < endPos - 25 && vcOfset.top - scrollTop - offset <= 0) { //Left condition is to get rid of a sticky zone on extremely short posts. Right condition is for scrolling down into the sticky zone from outside.
                    if (endPos - realHeight > scrollTop + offset + 25 || endPos - scrollTop - realHeight - offset >= 0) { //Left condition marks the bottom limit for the sticky zone. Right condition is for scrolling up into the sticky zone from outisde.
                        $vote.css({
                            position: 'fixed',
                            top: offset
                        });
                    } else {
                        //Stop stickiness when we've scrolled down past the sticky zone.
                        $vote.css({
                            position: 'absolute',
                            top: endPos - realHeight //Leave the button at its bottommost position
                        });
                    }
                } else {
                    $vote.removeAttr('style');
                }

                sox.helpers.observe($vote, function() { //Fix dismissable message boxes, like "Please consider adding a comment if you think this post can be improved." when downvoting
                    if ($vote.css("position") == "fixed") {
                        $vote.find('.message-dismissable').css({
                            position: "fixed"
                        });
                    }
                    else {
                        $vote.find('.message-dismissable').css({
                            position: "absolute",
                            "white-space": "nowrap"
                        })
                    }
                })
            });
        }
    },

The problem was that `votePos` changed its values weirdly, so I removed it in favor of `scrollTop + offset + 25`. I also fixed a few unrelated bugs with dismissible messages (i.e. messages that say "Please consider adding a comment if you think this post can be improved." or "You last voted on this question 1 hour ago. Your vote is now locked in unless this question is edited."), which is in the MutationObserver.

**Comment by shu8** [comment] 2017-02-22 22:11
@Sir-Cumference thanks so much!! I'll try it out and get it pushed ASAP! :)

**Comment by shu8** [comment] 2017-02-25 22:09
@Sir-Cumference I've pushed it in [dev 2.0.24](https://github.com/soscripted/sox/raw/dev/sox.user.js) now :) thanks so much for the fix!! :)

cc/ @wgrundlingh it's fixed!

**Closed by shu8** 2017-02-25 22:09 UTC
Labels: bug, confirmed, help wanted, in progress, ready

**Comment by Sir-Cumference** [comment] 2017-03-01 19:58
@shu8 I noticed that my solution made the vote buttons update slower and slower, the longer you wait after loading the page. The lag becomes really noticeable when you wait long enough:

![problem1](https://cloud.githubusercontent.com/assets/5375326/23478331/0cbad150-fe8f-11e6-8fa6-f4cc8900f198.gif)

You can see that the buttons go beyond the post for a split second. The culprit turned out to be the MutationObserver. It was supposed to solve this bug:

<img width="446" alt="screen shot 2017-03-01 at 2 57 28 pm" src="https://cloud.githubusercontent.com/assets/5375326/23478446/6b00f9d8-fe8f-11e6-85c7-cfaa7cc01b3a.png">

I removed it and wrote another way to fix the problem with the messages. I also rewrote some of my comments and removed some unnecessary parts of the code:

    stickyVoteButtons: function() {
        // Description: For making the vote buttons stick to the screen as you scroll through a post
        //https://github.com/shu8/SE_OptionalFeatures/pull/14:
        //https://github.com/shu8/Stack-Overflow-Optional-Features/issues/28: Thanks @SnoringFrog for fixing this!

        stickcells();
        $(document).on('sox-new-review-post-appeared', stickcells);

        $(window).scroll(function() {
            stickcells();
        });

        function stickcells() {
            var $votecells = $('.votecell');
            $votecells.css('min-width', '46px');

            $votecells.each(function() {
                var $topbar = $('.topbar'),
                    topbarHeight = $topbar.outerHeight(),
                    offset = (sox.location.on('/review') ? 60 : 10);

                if ($topbar.css('position') == 'fixed') offset += topbarHeight;

                var $voteCell = $(this),
                    $vote = $voteCell.find('.vote'),
                    vcOfset = $voteCell.offset(),
                    scrollTop = $(window).scrollTop(),
                    realHeight, endPos;

                if (sox.location.on('/review/suggested-edits/')) $vote.css('padding-top', '35px');

                if ($vote.length && $vote.children().last().length && $voteCell.next().length) { //These values strangely alternate between existing and not existing. This if statement insures we only get their values when they exist, so no errors.
                    realHeight = $vote.children(':not(:hidden, .message-dismissable)').last().offset().top + $vote.children(':not(:hidden, .message-dismissable)').last().height() - $vote.offset().top; //Get the original height; the difference between the last child and the first child's position
                    endPos = $voteCell.next().offset().top + $voteCell.next().height() - 51; //I think a bit above the end of the post (where the "edit", "delete", etc. buttons lie) is a good place to stop the stickiness.
                }

                $voteCell.on('DOMNodeInserted', function() { //Fix dismissable message boxes, like "Please consider adding a comment if you think this post can be improved." when downvoting
                    $vote.find('.message-dismissable').css({
                        position: "absolute",
                        "white-space": "nowrap"
                    })
                })

                if (vcOfset.top + realHeight < endPos - 25 && vcOfset.top < scrollTop + offset) { //Left condition is to get rid of a sticky zone on extremely short posts. Right condition allows stickiness unless we're above the post.
                    if (scrollTop + offset + realHeight < endPos) { //Allow stickiness unless we've scrolled down past the post.
                        $vote.css({
                            position: 'fixed',
                            top: offset
                        });
                    } else {
                        $vote.css({
                            position: 'absolute',
                            top: endPos - realHeight //Leave the button at its bottommost position
                        });
                    }
                } else {
                    $vote.removeAttr('style'); //Remove any stickiness
                }
            });
        }
    },

This should fix everything :)

**Comment by shu8** [comment] 2017-03-03 20:43
@Sir-Cumference thanks again! I'll get that added in ASAP, it's weird that the mutationobserver did that though, so that might be a bug in the observer itself -- I'll have a look at that as well.

I really appreciate the help! :)

**Comment by Sir-Cumference** [comment] 2017-03-03 22:45
@shu8 I can tell you that having anything in a MutationObserver, even console.log(), caused that problem. 😕
